<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<p><span style="font-size:10px;font-family:&quot;Open Sans&quot;,sans-serif">Это системное уведомление и отвечать на него не нужно.</span>
    <br /><span style="font-size:10px;font-family:&quot;Open Sans&quot;,sans-serif">Свои вопросы вы можете задать, обратившись в&nbsp;</span>
    <a href="mailto:site@saga.dn.ua" style="font-size:10px;font-family:&quot;Open Sans&quot;,sans-serif" target="_blank">службу поддержки.</a>
</p>
<table style="height:76px" width="750">
<tbody>
    <tr>
        <td>
            <a href="http://saga.diamonds"><img alt="logo_SAGA" src="http://saga.diamonds/uploads/email/logo.png" /></a>
        </td>
        <td style="text-align:right"><p style="text-align:right;font-family:&quot;Open Sans&quot;,sans-serif;font-size:14px;line-height: 1.5em;">Персональный консультант +38&nbsp;050&nbsp;470 97 41<br />
            Киевский бутик SA&amp;GA +38&nbsp;050&nbsp;339 97 57</p>
        </td>
    </tr>
</tbody>
</table>
<img alt="gift_for_registration" src="http://saga.diamonds/uploads/email/200UAH.jpg"/>
<h1 style="text-align: center; width: 750px; margin-top: 20px;"><?=$this->order->client_name?>!</h1>
<p style="line-height: 1.5em;text-indent: 2em;font-family:&quot;Open Sans&quot;,sans-serif;font-size:14px;">Добро пожаловать в Ювелирный дом <a href="http://<?=$this->siteName?>">SA&amp;GA</a>!</p>
<p style="line-height: 1.5em;text-indent: 2em;font-family:&quot;Open Sans&quot;,sans-serif;font-size:14px;width: 750px;text-align: justify;">Мы уже положили на Ваш счет 200 гривен, 
    которые можно использовать при заказе украшения через интернет-витрину Ювелирного бутика SA&amp;GA или при его приобретении в нашем ювелирном магазине.*</p> 
<p style="line-height: 1.5em;text-indent: 2em;font-family:&quot;Open Sans&quot;,sans-serif;font-size:14px;width: 750px;text-align: justify;">У нас действует накопительная система скидок. 
    О состоянии своего бонусного счета Вы сможете узнать у персонального консультанта по телефону +38 (050) 470-97-41 или, обратившись к нам по электронной почте 
    <a href="mailto:site@saga.diamonds">site@saga.diamonds</a></p>
<br />
<p style="line-height: 1.5em;font-family:&quot;Open Sans&quot;,sans-serif;font-size:14px;width: 750px;">Адреса магазинов</p>
<p style="line-height: 1.5em;font-family:&quot;Open Sans&quot;,sans-serif;font-size:14px;width: 750px;">г. Киев ул. Горького, 176 ТРЦ Ocean Plaza 1-й этаж, ювелирный квартал</p>
<p style="line-height: 1.5em;font-family:&quot;Open Sans&quot;,sans-serif;font-size:14px;width: 750px;">г. Краматорск ул. Шкадинова, 36</p>
<br/>
<img alt="respect" src="http://saga.diamonds/uploads/email/respect.jpg"/>
<br/><br/>
<div style="font-size: 0.7em; border-top: 1px solid grey;width: 400px;">* - условия для получения бонуса - совершение покупки от 3000 грн.</div> 
<br/><br/><br/><br/>
