<h1>Уважаемый <?=$this->order->client_name?>!</h1>
<p>Статус Вашего заказ в магазине <a href="<?=$this->siteHref?>"><?=$this->siteName?></a> был изменен</p>
<p>Текущий статус заказа: <?=$this->order_Status($this->order)?></p>
<h2>Содержимое заказа:</h2>

<table>
	<tr>
		<td>
		<?=$this->shipmentInfoHtml?>
		<?=$this->paymentInfoHtml?>
		</td>
	</tr>
</table>


<h1 style="width: 800px; text-align: center"><?=$this->translate('Заказ №%1$s', $this->order->id)?></h1>
<table width="800px" cellpadding="5" cellspacing="0" border="1">
    <tr>
        <th><?=$this->translate('#')?></th>
        <th><?=$this->translate('Товар')?></th>
        <th><?=$this->translate('Кол-во')?></th>
        <th><?=$this->translate('Цена за ед.')?></th>
        <th><?=$this->translate('Стоимость')?></th>
    </tr>
    <? $i = 0 ?>
    <? foreach ($this->order->items as $item) { ?>
        <tr>
            <td align="right">
                <?=( ++ $i)?>
            </td>
            <td>
                <strong><?=$item['name']?></strong>
                <? if ( ! empty($item['attributes_text'])) { ?>
                	<br/>
                    <?=$item['attributes_text']?>
                <? } ?>
            </td>
            <td align="right">
                <?=$item['qty']?>
            </td>
            <td align="right"><?=$this->order_Summ($item['price'], $this->order->currency)?></td>
            <td align="right"><?=$this->order_Summ( (float) $item['price'] * (float) $item['qty'], $this->order->currency)?></td>
        </tr>
    <? } ?>
</table>
<div style="padding-top: 20px;padding-left: 500px">
<?=$this->order_Total($this->order, TRUE, TRUE)?>
</div>


