
	<?$errors = array_merge($this->form->getErrors(), $this->form->getErrorMessages())?>
	<form  enctype="multipart/form-data"<?foreach ($this->form->getAttribs() as $name=>$value){?><?=$name?>="<?=$value?>"<?}?>>
	<?if ($this->form->getText() !== NULL) {?>
	<p class="question_form_header"><?=$this->form->getText()?></p>
		<?}?>
	<? foreach ($errors as $error_key=>$error_text) { ?>
	   <? if (is_numeric($error_key)) { ?>
		   <p class="question_form_header"><?=$error_text?></p>
	   <? } ?>
	<? } ?>
	<? $buttons = array() ?>
	<? $hiddens = array() ?>
	<? $inputs = array() ?>
	<? foreach ($this->form->getElements() as $el) {?>
		<? if (($el instanceof Zend_Form_Element_Submit) OR ($el instanceof Zend_Form_Element_Button)) { ?>
			<? $buttons[]=$el ?>
		<? } else if ($el instanceof Zend_Form_Element_Hidden) { ?>
			<? $hiddens[]=$el ?>
		<? } else { ?>
			<? $inputs[]=$el ?>
		<? } ?>
	<? } ?>
		<? foreach ($inputs as $el) {?>
			<div><? $label = $el->getLabel() ?>
			
				<? if ( ! empty($label)) { ?><label for="<?=$el->getName()?>"><?=$label?><? //if ($el->isRequired()) {?> <?//=$this->formMarkerRequired()?><?// } ?> </label><? } ?>
					<? if ($errors[$el->getName()]) { ?>
						<div class="red" style="color:red">
						<?=$this->form->getElementErrorsFormatted($el->getName(), $errors[$el->getName()])?>
						</div>
					<? } ?>
					<? if (in_array($el->getType(), array('Zend_Form_Element_Text', 'Zend_Form_Element_Password'))) { ?>
							<? $el->setAttrib('class', 'input') ?>
					<? } else if ($el->getType() == 'Zend_Form_Element_Select') { ?>
							<? $el->setAttrib('class', 'select') ?>
					<? } else if ($el->getType() == 'Zend_Form_Element_Textarea') { ?>
							<? $el->setAttrib('class', 'textarea') ?>
					<? } ?>
					<? $el->setDecorators(array('ViewHelper')) ?>
					<?=$el->render()?>
				</div>
		<? } ?>
	
<div class="cleaner"></div>
	<? foreach ($buttons as $btn) { ?>
		<?=$btn->render()?>
	<? } ?>
	<? foreach ($hiddens as $el) { ?><?=$el->render()?><? } ?>
	</form>
