<div class="mcol">
	<div class="title_h3">
		<h3>Редактирование персональных данных</h3>
	</div>
	<span class="inputRequirementTitle">поля, отмеченные *, обязательны для заполнения</span>
	<?=$this->renderForm($this->form)?>
	<a href="<?=$this->url(array(), 'shop-my_cabinet')?>"><img src="<?=$this->skin()->url()?>images/button_back.jpg" alt="Назад" title=" Назад " class="button_info" style="border: none;" /></a>
</div>