$(gridSelector+" input[name=spec_as_html]").live('click', function(){
    var rowId = $($(this).parents("div.tablediv").get(0)).attr("id");
    rowId = rowId.substr(String("bundles_").length); /* ltrim "bundles_" */
    var subrowId = $($(this).parents("tr").get(0)).attr("id");
    var subgridId = $($(this).parents("table").get(0)).attr("id");
    $("#items_for_sub_wrap").data("subgridId", subgridId);
    $("#items_for_sub_wrap").data("subrowId", subrowId);
    $("#items_for_sub_wrap").data("rowId", rowId);
    $("#items_for_sub_wrap").show();
    $("#items_for_sub").trigger("reloadGrid");
});