gridNav
.navSeparatorAdd(pagerSelector)
.navButtonAdd(pagerSelector, {
    caption: "",
    title: "<?=$this->translate('Добавить выбранные строки')?>",
    buttonicon: "ui-icon-check",
    onClickButton: function(){
    
        var subgrid = jQuery("#"+jQuery("#items_for_sub_wrap").data("subgridId"));
        var subgrid_row = jQuery("#items_for_sub_wrap").data("subrowId");
        var grid_row = jQuery("#items_for_sub_wrap").data("rowId");
        var selrows = jQuery(gridSelector).getGridParam("selarrrow");
        
        var id;
        var rowData;
        var i = 0;
        
        for (sid in selrows) {
            id = selrows[sid]; 
            rowData = jQuery(gridSelector).getRowData(id);
            if (i == 0) {
                subgrid.setCell(subgrid_row, "item_id", id);
                subgrid.setCell(subgrid_row, "sku", rowData.sku);
                subgrid.setCell(subgrid_row, "alias", "");
                subgrid.setCell(subgrid_row, "spec_as_html", rowData.spec_as_html);
                subgrid.setCell(subgrid_row, "price", rowData.price);
                subgrid.saveRow(subgrid_row, null, null, {row_id: grid_row, id: subgrid_row, item_id: id, sku: rowData.sku, spec_as_html: rowData.spec_as_html, price: rowData.price});                
            }
            else {
                subgrid.addRowData("new_subrow", 
                    {
                        item_id: id,
                        sku: rowData.sku,
                        alias: "",
                        spec_as_html: rowData.spec_as_html,
                        price: rowData.price
                    }, 
                    "last");
                subgrid.saveRow(
                    "new_subrow", null, null,
                    {
                        row_id: grid_row,
                        id: "new_subrow",
                        item_id: id,
                        sku: rowData.sku,
                        alias: "",
                        spec_as_html: rowData.spec_as_html,
                        price: rowData.price
                    }
                );
            }
            ++ i;
        }        
                
        jQuery("#items_for_sub_wrap").hide();
        jQuery("#bundles").collapseSubGridRow(grid_row);
        jQuery("#bundles").expandSubGridRow(grid_row);
                    
        return false;
    }
})
.navSeparatorAdd(pagerSelector)
.navButtonAdd(pagerSelector, {
    caption: "",
    title: "<?=$this->translate('Закрыть')?>",
    buttonicon: "ui-icon-close",
    onClickButton: function(){
        $("#items_for_sub_wrap").hide();
        return false;
    }
})
;

$("#items_for_sub_search").filterGrid(gridId,{
    gridModel:true,
    gridNames:true,   
    formtype:"vertical",
    enableSearch: true,   
    enableClear: true,
    autosearch: false 
});
