<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'shop-index')?>">Главная<span></span></a>
        <span class="current">Карта сайта</span>
    </div>
</div>
<div class="content page">
    <div class="center">
        <div class="text">
                <h2>Карта сайта</h2>
                <p>
                    <?foreach ($this->pages as $page){?>
                        <?if ($page->status == 1){?>                            
                            <a href="<?=$this->url(array('seo_id' => $page->seo_id), 'shop-page')?>"><?= $page->title?></a></br>
                        <?}?>
                    <?}?>
                </p>
				<br>
				<h3>Каталог</h3>
                <p>
                    <?foreach ($this->categories as $category){?>
                        <?if ($page->status == 1){?>                            
                            <a href="<?=$this->url(array('seo_id' => $category->seo_id), 'shop-catalog')?>"><?= $category->name?></a></br>
                        <?}?>
                    <?}?>
                </p>
            </div>
    </div>
    <div class="cleaner"></div>
</div>
    





