<? $this->pageTitle($this->translate('Заказы')); ?>
<div class="widget-box collapsible">
    <div class="widget-title">
        <a href="#collapseTwo" data-toggle="collapse">
			<span class="icon"><i class="icon-search"></i></span>
                <h5><?=$this->translate('Поиск')?></h5>
        </a>
    </div>
    <div class="collapse" id="collapseTwo">
        <div class="widget-content">
                <?=$this->filter?>
        </div>
    </div>
</div>
<?=$this->adminMassForm('formStart')?>
<div class="widget-box collapsible">
    <div class="widget-title">
        <a href="#collapseThree" data-toggle="collapse">
			<span class="icon"><i class="icon-pencil"></i></span>
                <h5><?=$this->translate('Действия с заказами')?></h5>
        </a>
    </div>
    <div class="collapse" id="collapseThree">
        <div class="widget-content">
                 <?=$this->adminMassForm()->setMassActions(array('delete'))->adminMassForm('actions')?>
        </div>
    </div>
</div>

<div class="widget-box table">
    <div class="widget-title"><h5><?=$this->translate('Заказы')?></h5></div>
    <div class="widget-content nopadding">  
        <? $i = 0 ?>
        <table cellspacing="0" class="table table-bordered table-striped table-hover table-no-external-border">
            <thead>
                <tr>
                    <th style="width: 51px;text-align: center;"><?=$this->adminMassForm('checkAll')?></th>
                    <th><?=$this->translate('Дата')?></th>
                    <th><?=$this->translate('Номер')?></th>
                    <th><?=$this->translate('Клиент')?></th>
                    <th><?=$this->translate('Сумма')?></th>
                    <th><?=$this->translate('Состояние')?></th>
                    <th class="actions2" width="12%"><?=$this->translate('Actions')?></th>
                </tr>
            </thead>

        <? if ($this->orders->count()) { ?>
            <? foreach ($this->orders as $row) { ?>

                    <?//Стиль документа
                    if($row->status == 0 || $row->status == 6 /*error*/){
                        $style = ' class="error-doc-status"'; 
                    }elseif($row->status == 4 /*success*/){ 
                        $style = ' class="success-doc-status"'; 
                    }elseif($row->status == 1 || $row->status == 2|| $row->status == 3 || $row->status == 5  /*processed*/){ 
                        $style = ' class="processed-doc-status"';
                    }else{
                        $style = '';
                    }?>
                    
                <tr<?=$style?>>
              
                    <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
                    <td> <?=$this->formatDate($row['date_added'], TRUE)?><br /></td>
                    <td> <?=$row['id']?></td>
                    <td> <?=$row['client_name']?></td>
                    <td> <?=$this->order_Summ($row['total'], $row['currency'])?><br /></td>
                    <td> <?=$this->order_Status($row)?></td>
                    <td class="actions2">
                        <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit', 'admin-order', 'checkout')?>"><?=$this->translate('Edit')?></a>
                         /
                        <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete', 'admin-order', 'checkout')?>"><?=$this->translate('Delete')?></a>
                        
                        <!--a class="txt_blue" target="_blank" href="<?=$this->stdUrl(array('id'=>$row['id']), 'print', 'order', 'shop')?>"><?=$this->translate('Печать')?></a-->
                    </td>
                </tr>

                <? ++$i ?>
            <? } ?>
        <? } else { ?>
              <tr>
                <td colspan="6">
                    <?=$this->translate('Нет заказов')?>
                </td>
              </tr>
        <? } ?>
        </table>
    </div>
    <?=$this->paginationControl($this->orders)?>
    <?=$this->adminMassForm('formEnd')?>
</div>




