<? $ucfId = ucfirst($this->id)?>
<? $this->headScript('SCRIPT', '

    function flexigrid'.$ucfId.'New(command, grid)
    {
        $("#dialog'.$ucfId.'New :input").val("");
        $("#dialog'.$ucfId.'New").data("grid", grid);
        $("#dialog'.$ucfId.'New").dialog("open");
    }

    function flexigrid'.$ucfId.'Edit(command, grid)
    {
        if ($(".trSelected", grid).length<1) {
            alert("'.$this->translate('Не выбрана строка для редактирования').'");
            return;
        }
        var rowId = $(".trSelected", grid).eq(0).attr("id");
        $("#dialog'.$ucfId.'Edit").data("rowId", rowId);
        $("#dialog'.$ucfId.'Edit").data("grid", grid);
        $.getJSON("'.$this->urlGet.'", {"rowId": rowId}, function(rowData){
            var el;
            var inp;
            for (el in rowData) {
            	inp = $("#dialog'.$ucfId.'Edit #"+el);
            	if (inp.size() > 0) {
            		if (inp.get(0).type == "textarea") {
            			inp.html(rowData[el]);
            		}
            		else {
            			inp.val(rowData[el]);
            		}
            	}
            }
            $("#dialog'.$ucfId.'Edit div.bDiv>table").flexReload();
            $("#dialog'.$ucfId.'Edit").dialog("open");
        });
    }

    function flexigrid'.$ucfId.'Delete(command, grid)
    {
        if ($(".trSelected", grid).length<1) {
            alert("'.$this->translate('Не выбраны строки для удаления').'");
            return;
        }


        if (confirm("'.$this->translate('Вы действительно хотите удалить выбранные строки').'?")) {
            var postData = "";
            $(".trSelected", grid).each(function(i){
                postData += "&rows["+i+"]="+$(this).attr("id");
            });
            $.post("'.$this->urlDelete.'", postData, function(res){
                $("div.bDiv>table").flexReload();
            });
        }


    }


    $(function(){
        $("body").append('.Zend_Json::encode('<div id="dialog'.$ucfId.'New">'.$this->renderForm($this->formNew).'</div>').');
        $("body").append('.Zend_Json::encode('<div id="dialog'.$ucfId.'Edit">'.$this->renderForm($this->formEdit).'</div>').');
        $("body").append('.Zend_Json::encode('<div id="dialog'.$ucfId.'Select">'.$this->renderForm($this->formSelect).'</div>').');

        $("#dialog'.$ucfId.'New #name").after("<button style=\"border: 1px solid #CCCCCC; margin-left: 3px; background-color: #F9F9F9; border-radius: 4px;\" id=\"select_button\">...</button>");
        $("#dialog'.$ucfId.'New #select_button").click(function(e){
        	e.preventDefault();
        	$(".pSearch").click();
        	$("#dialog'.$ucfId.'Select").data("mode", "New");
        	$("#dialog'.$ucfId.'Select").dialog("open");
        });
        
        $("#dialog'.$ucfId.'Edit #name").after("<button style=\"border: 1px solid #CCCCCC; margin-left: 3px; background-color: #F9F9F9; border-radius: 4px;\" id=\"select_button\">...</button>");
        $("#dialog'.$ucfId.'Edit #select_button").click(function(e){
        	e.preventDefault();
	       	$(".pSearch").click();
	       	$("#dialog'.$ucfId.'Select").data("mode", "Edit");
        	$("#dialog'.$ucfId.'Select").dialog("open");
        });
        

        $("#dialog'.$ucfId.'New").dialog({
            autoOpen: false,
            closeOnEscape: true,
            width: 700,
            title: "'.$this->translate('Новый товар').'",
            buttons: {
                "'.$this->translate('Ok').'":
                        function(){
                            var $this = $(this);
                            var grid = $this.data("grid");
                            var data = $(":input", this).serializeArray();
                            var postData = {};
                            for (el in data) {
                                postData[data[el].name] = data[el].value;
                            }
                            if (postData.name.replace(/^\s+|\s+$/, "").length == 0) {
                            	alert("'.$this->translate('Введите наименование или выберите товар из каталога').'");
                            	return;
                            }
                            if ((parseFloat(postData.price) <= 0) || (isNaN(parseFloat(postData.price)))) {
                            	alert("'.$this->translate('Введите цену товара').'");
                            	return;
                            }
                            if ((parseInt(postData.qty) <= 0) || (isNaN(parseInt(postData.qty)))) {
                            	alert("'.$this->translate('Введите количество товара').'");
                            	return;
                            }
                            $.post("'.$this->urlNew.'", postData, function(res){
                                if (res=="ok") {
                                    $this.dialog("close");
                                    $("div.bDiv>table").flexReload();
                                }
                                else {
                                    alert("'.$this->translate('Ошибка').': "+res);
                                }
                            });
                        },
                "'.$this->translate('Cancel').'":
                        function(){
                            $(this).dialog("close");
                        }
            }
        });

        $("#dialog'.$ucfId.'Edit").dialog({
            autoOpen: false,
            closeOnEscape: true,
            width: 700,
            title: "'.$this->translate('Редактирование товара').'",
            buttons: {
                "'.$this->translate('Ok').'":
                        function(){
                            var $this = $(this);
                            var grid = $this.data("grid");
                            var data = $(":input", this).serializeArray();
                            var postData = {};
                            for (el in data) {
                                postData[data[el].name] = data[el].value;
                            }
                            postData.rowId = $this.data("rowId");
                            if (postData.name.replace(/^\s+|\s+$/, "").length == 0) {
                            	alert("'.$this->translate('Введите наименование или выберите товар из каталога').'");
                            	return;
                            }
                            if ((parseFloat(postData.price) <= 0) || (isNaN(parseFloat(postData.price)))) { 
                            	alert("'.$this->translate('Введите цену товара').'");
                            	return;
                            }
                            if ((parseInt(postData.qty) <= 0) || (isNaN(parseInt(postData.qty))) || (+postData.qty != postData.qty || postData.qty.indexOf(".") != -1)) {
                            	alert("'.$this->translate('Введите количество товара').'");
                            	return;
                            }
                            $.post("'.$this->urlEdit.'", postData, function(res){
                                $this.dialog("close");
                                $("div.bDiv>table").flexReload(); /* not $("div.bDiv>table", grid) !!! */
                            });
                        },
                "'.$this->translate('Cancel').'":
                        function(){
                            $(this).dialog("close");
                        }
            }
        });

        $("#dialog'.$ucfId.'Select").dialog({
            autoOpen: false,
            closeOnEscape: true,
            width: 500,
            height: 540,
            title: "'.$this->translate('Выбор товара из каталога').'",
            buttons: {
                "'.$this->translate('Ok').'":
                        function(){
                            var $this = $(this);
                        	var mode = $this.data("mode");
                        	
                        	var selectedRows = $("#dialog'.$ucfId.'Select .flexigrid table .trSelected");
                            if (selectedRows.length<1) {
                                alert("'.$this->translate('Выберите товар').'");
                                return;
                            }
                            
                        	var selectedRow = selectedRows.eq(0);
                        	var catalog_item_id = selectedRow.attr("id").substr(3);
                        	var name = $("td[abbr=name]", selectedRow).text();
                        	var price = $("td[abbr=price]", selectedRow).text();
                        	var attributes_text = $("td[abbr=attributes_text]", selectedRow).text();                        	
                        	
                        	$("#dialog'.$ucfId.'"+mode+" #catalog_item_id").val(catalog_item_id);
                        	$("#dialog'.$ucfId.'"+mode+" #name").val(name);
                        	$("#dialog'.$ucfId.'"+mode+" #price").val(price);
                        	$("#dialog'.$ucfId.'"+mode+" #attributes_text").val(attributes_text);
                        	
                        	$this.dialog("close");                        	
                        },
                "'.$this->translate('Cancel').'":
                        function(){
                            $(this).dialog("close");
                        }
            }
        });        


    });

') ?>