<h2><?=$this->translate('Доска объявлений')?></h2>

<table width="100%" cellpadding="0" cellspacing="0">
<tr>
    <td align="right">
        <a href="<?=$this->stdUrl(array('reset'=>TRUE), 'edit', 'advert', 'social')?>" class="btn2"><?=$this->translate('New')?></a>
    </td>
</tr>
</table>

<? $groupKey = NULL ?>
<? $cnt = 0 ?>
<? foreach ($this->adverts as $row) { ?>
    <? if ($groupKey != $row['group_key']) { ?>
        <? if ($cnt > 0) { ?>
              </table>
            </div>
        <? } ?>
            <a href="#" no_ajax_wj_replace="1" class="mail_subject mail_subject_<?=$row['group_key']?>"><?=$this->advert_Title($row)?> <img src="<?=$this->skin()->url()?>images/arr_sect_up.gif" alt="" width="8" height="8" border="0" /></a>
            <div class="mail_row mail_row_<?=$row['group_key']?>">
              <table cellspacing="0" class="tbl" style="width: 100%; margin: 0px;">
        <script type="text/javascript">
                $(document).ready(function(){
                    $(".mail_subject_<?=$row['group_key']?>").unbind();
                    $(".mail_subject_<?=$row['group_key']?>").click(function(e){
                        e.preventDefault();
                        var visibles = $(".mail_row_<?=$row['group_key']?>:visible");
                        var hiddens = $(".mail_row_<?=$row['group_key']?>:hidden");
                        if (visibles.length > 0) {
                            visibles.hide();
                            $(this).children("img").attr("src", "<?=$this->skin()->url()?>images/arr_sect_down.gif");
                        }
                        else {
                            hiddens.show();
                            $(this).children("img").attr("src", "<?=$this->skin()->url()?>images/arr_sect_up.gif");
                        }
                    });
                    $(".mail_subject_<?=$row['group_key']?>").click();
                });
        </script>
        <? $talking = $row['group_key'] ?>
    <? } ?>

        <tr <?=$this->cycle(array('', 'class="alt_row"'))->next()?>>
          <td style="text-align: center; vertical-align: middle;" width="10%"><?=$this->formatDate($row['date_added'])?><br />
            <span class="txt_green"><?=$this->formatTime($row['date_added'])?></span></td>
          <td>
            <?=$row['text']?>
            <br/>
            <strong>Кол-во: <?=$row['qty']?> шт.</strong>
            <br/>
            <strong>Цена: <?=$row['price']?> руб.</strong>
          </td>
          <td class="admin_content" width="15%" align="center">
            <? if ($row['adder_id'] == $this->user['id']) { ?>
                <a href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit', 'advert')?>" class="act_edit"><?=$this->translate('Edit')?></a>
                /
                <a href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete', 'advert')?>" class="act_delete"><?=$this->translate('Delete')?></a>
                <?/*?>
                <br />
                <a href="<?=$this->stdUrl(array('id'=>$row['id']), 'ajax-deactivate', 'advert')?>"><?=$this->translate('Deactivate')?></a>
                <?*/?>
            <? } else { ?>
                <a href="<?=$this->url(array('login'=>$row['adder_login']), 'user_profile')?>"><?=$row['adder_name']?></a>
            <? } ?>
          </td>
        </tr>

    <? ++ $cnt ?>
<? } ?>

    <? if ($cnt > 0) { ?>
      </table>
    </div>
    <? } ?>

    <?=$this->paginationControl($this->adverts)?>


<br><div class="attention">
  <div class="wrapp">
    <?=$this->translate('Если Вы хотите купить или продать ТА оставьте сообщение. Для этого нажмите кнопку "Создать".')?>
  </div>
</div>

