<?=$this->headScript(Zend_View_Helper_HeadScript::SCRIPT, '
    $(function(){
    	bindGlobalEvent(EVENT_SHOPPING_CART_UPDATED, function(e){
    		var div = $("#box_shopping_cart");
    		$.get(div.attr("href"), function(html){div.replaceWith(html);});
    	});
    });
')?>


<div id="box_shopping_cart" class="widjet basket" href="<?=$this->stdUrl(NULL, 'ajax-get-cart-box', 'cart', 'checkout')?>">
    <div class="padd">
        <div class="title"><?=$this->translate('Корзина')?>:</div>
        <? if ($this->positionQty > 0) { ?>
	        <p><?=$this->translate('Товаров: %1$s', $this->totalQty)?>  (<a href="<?=$this->cartLink?>"><?=$this->translate('смотреть')?></a>)</p>
    	    <p><?=$this->translate('На сумму:  %1$s', $this->cart_Summ($this->totalSumm))?> </p>
        	<div><img src="<?=$this->skin()->url()?>images/spacer.gif" width="50" height="4" border="0" /></div>
        	<div class="box-basket"><a href="<?=$this->cartLink?>" class="basket-submit"><?=$this->translate('Оформить покупку')?></a></div>
        <? } else { ?>
        	<p><?=$this->translate('Корзина пустая')?></p>
        <? } ?>
        <div class="cleaner"></div>
    </div>
</div>

<div id="settings"><a href="<?=$this->cartLink?>"><img src="<?=$this->skin()->url()?>images/top/sett.gif" width="10" height="10" border="0" /></a></div>
