<h2><?=$this->translate(isset($this->values['id'])?'Edit attribute':'Create attribute')?></h2>

<?=$this->renderForm($this->form)?>

<? $this->headScript('SCRIPT', '
        function reloadAttributeValueFields()
        {
            var fieldType = $("form#attribute_edit select#type");
            var fieldDefVal = $("form#attribute_edit #default_value");
            var defVal = fieldDefVal.val();
            $.getJSON("'.$this->stdUrl(array('reset'=>TRUE), 'ajax-get-value-fields', 'admin-attribute', 'catalog').'", 
                {type: fieldType.val(), default_value: defVal},  
                function(resp) {
                    fieldDefVal.replaceWith(resp.fieldDefaultValue);
                }
            );
        }     

        $(function(){
            $("form#attribute_edit select#type").change(reloadAttributeValueFields);
        });
');
?>