
<div style="width: 100%">
    <h2 style="float: left"><?=$this->translate('Предварительные заказы')?></h2>
</div>

<div class="cleaner">&nbsp;</div>
<?=$this->filter?>
<div class="cleaner">&nbsp;</div>

<?=$this->adminMassForm('formStart')?>
<?=$this->adminMassForm('actions')?>

<? $i = 0 ?>

    <table cellspacing="0" class="tbl">
      <tr>
        <th width="50px"><?=$this->adminMassForm('checkAll')?></th>
        <th><?=$this->translate('Дата')?></th>
        <th><?=$this->translate('Номер')?></th>
        <th><?=$this->translate('Клиент')?></th>
        <th><?=$this->translate('Сумма')?></th>
        <th class="actions2"><?=$this->translate('Actions')?></th>
      </tr>

<? if ($this->preorders->count()) { ?>
    <? foreach ($this->preorders as $row) { ?>
          <tr >
            <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
            <td> <?=$this->formatDate($row['date_added'], TRUE)?><br /></td>
            <td> <?=$row['id']?></td>
            <td> <?=$row['client_name']?></td>
            <td> <?=$this->order_Summ($row['total'], $row['currency'])?><br /></td>
            <td class="actions2">
                <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit', 'admin-preorder', 'checkout')?>"><?=$this->translate('Edit')?></a>
                 /
                <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete', 'admin-preorder', 'checkout')?>"><?=$this->translate('Delete')?></a>
            </td>
          </tr>

        <? ++$i ?>
    <? } ?>

<? } else { ?>
      <tr>
        <td colspan="6">
            <?=$this->translate('Пока нет предварительных заказов')?>
        </td>
      </tr>
<? } ?>

    </table>


    <?=$this->adminMassForm('formEnd')?>

    <?=$this->paginationControl($this->preorders)?>





