<? if ($this->user) { ?>
<? } ?>
<div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav btn-group">
        <!--li class="btn btn-inverse"><a title="" href="<?=$this->stdUrl(array('reset' => true),  'syncronize', 'admin-index')?>"><i class="icon icon-refresh"></i><span class="text blue-name"> Cинхронизация</span></a></li-->
            <li class="btn btn-inverse" ><a title="" href="#"><i class="icon icon-user"></i><span class="text blue-name">
            <? if (count($this->bindedUsers) > 1) { ?>
                <?=$this->formSelect('id', $this->user['id'], array('onChange' => 'this.form.submit()'), $this->bindedUsers)?>
            <? } else { ?>
                <?= $this->user['name']; ?>
            <? } ?>
            </span></a></li>
            
            <li class="btn btn-inverse"><a title="" href="<?=$this->stdUrl(array('reset'=>TRUE), 'logout', 'admin-auth', 'kernel')?>"><i class="icon icon-share-alt"></i> <span class="text">Выйти</span></a></li>
        </ul>
    </form>
</div>
