<?
$this->headStyle('
    strong.pointed:hover, span.pointed:hover {
        cursor:pointer;
    }
');
?>

<h2><?=$this->translate('Новости, акции, скидки')?></h2>
<? $topic = NULL ?>
<? $cnt = 0 ?>
<? $i = 0 ?>
<? foreach ($this->news as $row) { ?>
    <? if ($topic != $row['ntopic_id']) { ?>
        <p class="close_rows">&nbsp;</p>
        <p class="news_title">
            <a href="<?=$this->stdUrl(array('topic_id'=>$row['ntopic_id']), 'topic', 'news')?>" class="all_news">Читать все</a>
            <strong class="pointed ntopic" ntopicid="<?=$row['ntopic_id']?>" ntopicnum="<?=$i?>"><?=$row['ntopic_name']?></strong>
            <? if ( (int) $row['ntopic_subscribed'] > 0) { ?>
                (<span href="<?=$this->stdUrl(array('topic_id'=>$row['ntopic_id']), 'ajax-subscribe', 'news')?>" class="pointed subscribe">Отписаться от рассылки</span>)
            <? } else { ?>
                (<span href="<?=$this->stdUrl(array('topic_id'=>$row['ntopic_id']), 'ajax-subscribe', 'news')?>" class="pointed subscribe">Подписаться на рассылку</span>)
            <? } ?>
        </p>
        <? $topic = $row['ntopic_id'] ?>
        <? $cnt = 0 ?>
    <? } ?>
    <? if ($cnt < $this->rowsPerTopic) { ?>
<p class="date news_row_ntopic_<?=$row['ntopic_id']?>"><?=$this->formatDate($row['date_publish'])?></p>
<div class="<?=$this->cycle(array('news_row','news_alt_row'))->next()?> news_row_ntopic" ntopicid="<?=$row['ntopic_id']?>">
  <a href="<?=$this->url(array('seo_id'=>$row['seo_id']), 'news_detailed')?>"><h3><?=$row['title']?></h3></a>
  <p><?=$row['announce']?></p>
</div>
    <? } ?>
    <? ++ $cnt ?>
    <? ++ $i ?>
<? } ?>


<p class="close_rows">&nbsp;</p>



<?
    $this->headScript('SCRIPT', '
        $(document).ready(function(){
            $(".ntopic").click(function(e){
                e.preventDefault();
                var $this = $(this);
                var ntopic = $this.attr("ntopicid");
                var ntopicNum = $this.attr("ntopicnum");
                var row = $(".news_row_ntopic[ntopicid="+ntopic+"]");
                if (row.is(":visible")) {
                    row.hide();
                }
                else {
                    row.show();
                }
            });

            /*$(".ntopic[ntopicnum!=0]").click();*/

            $("span.subscribe").click(function(e){
                e.preventDefault();
                var $this = $(this);
                $.get($this.attr("href"), function(data){
                    $this.html(data);
                });
            });

        });
    ');
?>
