
<p class="news_title"><strong>Новости на тему: <?=$this->news->getIterator()->current()->ntopic_name?></strong></p>
<? $topic = NULL ?>
<? $cnt = 0 ?>
<? foreach ($this->news as $row) { ?>
<p class="date"><?=$this->formatDate($row['date_publish'])?></p>
<div class="<?=$this->cycle(array('news_row','news_alt_row'))->next()?>">
  <a href="<?=$this->url(array('seo_id'=>$row['seo_id']), 'news_detailed')?>"><h3><?=$row['title']?></h3></a>
  <p><?=$row['announce']?></p>
</div>
<? } ?>

<p class="close_rows">&nbsp;</p>

<?=$this->paginationControl($this->news)?>

