<h2><?=$this->translate('Производители')?></h2>

<?=$this->filter?>

<?=$this->adminMassForm('formStart')?>
<?=$this->adminMassForm('actions')?>

<? $i = 0 ?>

    <table cellspacing="0" class="tbl">
      <tr>
        <th width=10%"><?=$this->adminMassForm('checkAll')?></th>
        <th><?=$this->translate('Название')?></th>
        <th><?=$this->translate('Логотип')?></th>
        <th class="actions2"><?=$this->translate('Actions')?></th>
      </tr>

<? foreach ($this->manufacturers as $row) { ?>
      <tr >
        <td width=10%"> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
        <td> <?=$row['name']?> </td>
        <td> <?=$this->html_Img($row['rc_id_preview'])?></td>
        <td class="actions2">
            <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit', 'admin-manufacturer', 'catalog')?>"><?=$this->translate('Edit')?></a>
             /
            <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete', 'admin-manufacturer', 'catalog')?>"><?=$this->translate('Delete')?></a>
        </td>
      </tr>

    <? ++$i ?>
<? } ?>


    </table>


    <?=$this->adminMassForm('formEnd')?>

    <?=$this->paginationControl($this->manufacturers)?>


  <a href="<?=$this->stdUrl(array('reset'=>TRUE), 'edit', 'admin-manufacturer', 'catalog')?>" class="btn2"><?=$this->translate('New')?></a>

