<?
$n = abs($this->items_count) % 100;
$n1 = $n % 10;

if ($n > 10 && $n < 20) {
    $countName = 'изделий';
} elseif ($n1 > 1 && $n1 < 5) {
    $countName = 'изделия';
} elseif ($n1 == 1) {
    $countName = 'изделие';
} else {
    $countName = 'изделий';
} ?>
<script type="text/javascript">
    $(function() {
        win_width = $(window).width();
        $('#toTop').css('left',(win_width+980)/2)
        $(window).scroll(function() {
            if($(this).scrollTop() != 0) {
                $('#toTop').fadeIn();
            } else {
                $('#toTop').fadeOut();
            }
        });
        $('#toTop').click(function() {
            $('body,html').animate({scrollTop:0},800);
        });
    });
</script>
<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'shop-index')?>">Главная<span></span></a>
        <span class="current"><?= $this->category->name?></span>
    </div>
</div>
<script type="text/javascript">
    url=window.location.toString();
    if(url.substr(-28,28)=="catalog-klassika-brilliantov"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-46,46)=="catalog-klassicheskie-ukrashenija-s-izumrudami"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_j.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-23)=="catalog-cvetnye-sapfiry"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_e.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-15,15)=="catalog-sapfiry"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_d.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-15,15)=="catalog-valenso"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_o.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-14,14)=="catalog-fusion"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_f.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-26,26)=="catalog-wedding-collection"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_w.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-13,13)=="catalog-black"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_c.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-17,17)=="catalog-saga-kids"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_k.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-14,14)=="catalog-enemal"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_z.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-27)=="catalog-podarki-vljublennym"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_r.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-16)=="catalog-zhemchug"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_s.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-14)=="catalog-rubiny"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_l.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-17)=="catalog-turmaliny"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_g.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-18)=="catalog-brillianty"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_y.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-17)=="catalog-exclusive"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_x.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-20)=="catalog-casual-style"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_v.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-24)=="catalog-shiny-collection"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_y.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
    if(url.substr(-20)=="catalog-magic-voyage"){
        css = ".collections .filter div,.collections .filter .filters{display:none !important;} .content .filter { background: url('uploads/ckfinder/images/banner_m.png') no-repeat scroll 0 0 transparent !important;";
        var head = document.getElementsByTagName('head')[0];
        var s = document.createElement('style');
        s.setAttribute('type', 'text/css');
        if (s.styleSheet) {   // IE
            s.styleSheet.cssText = css;
        } else {                // the world
            s.appendChild(document.createTextNode(css));
        }
        head.appendChild(s);
    }
</script>
<div class="content collections">
    <?= $this->category_Filter($this->category) ?>
    <div class="center">
        <script type="text/javascript">
            $(document).ready(function(){
                $('.show_info').mouseenter(function(){
                    $(this).parent().find('.info').show();
                })
                $('.item .info').mouseleave(function(){
                    $('.item .info').hide();
                })
            });
        </script>
        <? $counter = 0; ?>
        <div class="items">
            <span class="viewing">Найдено <?= $this->items_count ?> <?= $countName ?></span>
            <!--?php print_r('params = '.$this->search_params);?-->
            <?foreach($this->items as $key => $item){?>
                <? $counter++; ?>
                <?= ( $counter == 1  ) ? '<div class="block left">' : ''?>
                <?= ( $counter == 6  ) ? '<div class="cleaner"></div><div class="block line">' : ''?>
                <?= ( $counter == 11  ) ? '<div class="block right">' : ''?>
                    <div class="item <?= ( in_array($counter, array(2,3,8,12,13)) ) ? 'wide' : ''?><?= in_array($counter, array(5,10)) ? 'large' : ''?>" >
                        <? if (in_array($counter, array(5,10)))
                                $preview = 'rc_id_preview4';
                            elseif (in_array($counter, array(2,3,8,12,13)))
                                $preview = 'rc_id_preview3';
                            else $preview = 'rc_id_preview2';
                        ?>
 					<a class="show_info" href="javascript:void(0);">
                       <table class="items_align"><tr><td class="item_align">
                        <a class="items_align" href="<?=$this->url(array('category' => $this->category->seo_id, 'seo_id' => $item->seo_id), ( $this->category->seo_id == 'exclusive' ) ? 'shop-exclusive' : 'shop-item')?>">
                            <?if (isset($this->galleries[$item->id][0])){?>
                                <span><img  src="<?=App_Resource::getUploadsUrl($this->galleries[$item->id][0][$preview])?>" alt="" /></span>
                           <?}?>
                        </a>
                        </td></tr></table>
 					</a>
                       <!--a class="show_info" href="javascript:void(0);"></a-->
                        <a href="<?=$this->url(array('category' => $this->category->seo_id,'seo_id' => $item->seo_id), ( $this->category->seo_id == 'exclusive' ) ? 'shop-exclusive' : 'shop-item')?>">
                        <div class="info">
                            <div class="short">
                                <?= $item->brief?>
                                <!--?if( $item->price != 0 ){?>
                                    <div class="price">ЦЕНА<span><?=$item->price?> грн.</span></div-->
                                <!--?}?-->
                                <div>ПОДРОБНЕЕ</div>
                            </div>
                        </div>
                        </a>
                    </div>
                <?= ( in_array($counter, array(4,9,14)) || $key+1 == count($this->items) &&  !in_array($counter, array(5, 10))) ? '</div>' : ''?>
                <?if ($counter == 14){ $counter = 0; }?>
            <?}?>
        </div>
        <div class="cleaner"></div>
        <span class="items_preloader"></span>    
    </div>
</div>
<div id="toTop">^</div>
<script type="text/javascript">
    $(document).ready(function(){
        <?if ($this->items_count > 56){?>
            $(window).scrollTop(0);
            var page = 2;        
            var upload = true;
            $(window).scroll(function(){           
                var bottom = $(document).height() - $(window).height() - $(window).scrollTop();
                if (bottom < 1300 && upload == true) {
                    $('.items_preloader').toggle();
                    upload = false;
                    var last_position = $('.items .item').length;
                    $.ajax({
                        url: "<?= $this->url(array(), 'shop-ajax-get-next-items', true) ?>?<?= $_SERVER['QUERY_STRING'] ?>",
                        type: "POST",
                        data: { 
                                page: page,
                                param: <?= $this->category->id?>,
                                page_type: 'category'
                            },
                        dataType: "json",
                        success: function(data){
                            $('.items').append(data.items);
                            $('.items_preloader').toggle();
                            $('.show_info').bind("mouseenter", function(){
                                $(this).parent().find('.info').show();
                            });
                            $('.item .info').bind("mouseleave", function(){
                                $('.item .info').hide();
                            });
                            page++;
                            if ( $('.items .item').length < <?= $this->items_count?>)
                                upload = true;
                        }
                    })
                }
            });
        <?}?>
//        if(url.substr(-27)=="catalog-podarki-vljublennym"){
//            $('div.filter').html('<a href="/page/sv-valentine" class="banner_collection">&nbsp;</a>');
//        }
    });
</script>