
<div style="width: 100%">
    <h2 style="float: left"><?=$this->translate('Модули доставки')?></h2>
</div>

<div class="cleaner">&nbsp;</div>

<? $i = 0 ?>

    <table cellspacing="0" class="tbl">
      <tr>
        <th width="100px"><?=$this->translate('Sorting')?></th>
        <th><?=$this->translate('Название')?></th>
        <th width="100px"><?=$this->translate('Вкл./выкл.')?></th>
        <th class="actions2"><?=$this->translate('Actions')?></th>
      </tr>

<? if ($this->shipments->count()) { ?>
    <? foreach ($this->shipments as $row) { ?>
          <tr >
            <td> <?=$this->adminListSorting(array('method'=>$row['method'], 'action'=>'sorting-shipment'))?> </td>
            <td> <?=$row['title']?></td>
            <td align="center"> <?=$this->brule_OnOff($row, $this->stdUrl(array('method'=>$row['method'], 'on'=>1, 'reset'=>TRUE), 'on-off-shipment', 'admin-brule', 'checkout'),
                                                            $this->stdUrl(array('method'=>$row['method'], 'on'=>0, 'reset'=>TRUE), 'on-off-shipment', 'admin-brule', 'checkout'))?></td>
            <td class="actions2">
                <a class="act_edit" href="<?=$this->stdUrl(array('method'=>$row['method'], 'reset'=>TRUE), 'edit-shipment', 'admin-brule', 'checkout')?>"><?=$this->translate('Edit')?></a>
            </td>
          </tr>

        <? ++$i ?>
    <? } ?>

<? } else { ?>
      <tr>
        <td colspan="6">
            <?=$this->translate('Модули доставки не установлены, обратитесь в службу поддержки')?>
        </td>
      </tr>
<? } ?>

    </table>




