<? $dlgGetFrom = 'attributes_GetFromGroups'?>

<? $dlgAddToExist = 'attributes_AddToExistGroups'?>

<? $dlgAddToNew = 'attributes_AddToNewGroup'?>

<? /***************** prepare dialogs html ***************/ ?>

<? $contGetFrom = Zend_Json::encode($this->formGetFromGroups->attributes_from_groups->setDecorators(array('ViewHelper'))->render()
                                                .'<br/><br/><br/><br/>'
                                                .'<div style="text-align: right; width: 100%">'
                                                .'<a class="fm-button ui-state-default ui-corner-all fm-button-icon-left btn_submit" href="javascript:void(0)">Добавить<span class="ui-icon ui-icon-disk"></span></a>&nbsp;'
                                                .'<a class="fm-button ui-state-default ui-corner-all fm-button-icon-left btn_cancel" href="javascript:void(0)">Отменить<span class="ui-icon ui-icon-close"></span></a>'
                                                .'</div>')
?>

<? $contAddToExist = Zend_Json::encode($this->formAddToExistGroups->groups->setDecorators(array('ViewHelper'))->render()
                                                .'<br/><br/><br/><br/>'
                                                .'<div style="text-align: right; width: 100%">'
                                                .'<a class="fm-button ui-state-default ui-corner-all fm-button-icon-left btn_submit" href="javascript:void(0)">Добавить<span class="ui-icon ui-icon-disk"></span></a>&nbsp;'
                                                .'<a class="fm-button ui-state-default ui-corner-all fm-button-icon-left btn_cancel" href="javascript:void(0)">Отменить<span class="ui-icon ui-icon-close"></span></a>'
                                                .'</div>')
?>

<? $contAddToNew = Zend_Json::encode($this->renderForm($this->formAddToNewGroup, 'admin-item/simple-form.phtml')
                                                .'<br/><br/><br/><br/>'
                                                .'<div style="text-align: right; width: 100%">'
                                                .'<a class="fm-button ui-state-default ui-corner-all fm-button-icon-left btn_submit" href="javascript:void(0)">Добавить<span class="ui-icon ui-icon-disk"></span></a>&nbsp;'
                                                .'<a class="fm-button ui-state-default ui-corner-all fm-button-icon-left btn_cancel" href="javascript:void(0)">Отменить<span class="ui-icon ui-icon-close"></span></a>'
                                                .'</div>')
?>


<? /***************** prepare addon grid buttons ***************/ ?>

gridNav
.navSeparatorAdd(pagerSelector)
.navButtonAdd(pagerSelector, {
    caption: "",
    title: "<?=$this->translate('Добавить в шаблонные аттрибуты')?>",
    buttonicon: "ui-icon-copy",
    onClickButton: function(){
        var sels = jQuery(gridSelector).getGridParam("selarrrow")
        if ( ! sels.length) {
            alert("<?=$this->translate('Отметьте аттрибуты для добавления')?>");
            return false;
        }
        jQuery("#<?=$dlgAddToExist?>").data("grid", jQuery(gridSelector));
        viewModal("#<?=$dlgAddToExist?>", {gbox: "#gbox_"+gridId, jqm:true, jqM: true});
        return false;
        return false;
    }
})
.navButtonAdd(pagerSelector, {
    caption: "",
    title: "<?=$this->translate('Создать набор шаблонных аттрибутов')?>",
    buttonicon: "ui-icon-document-b",
    onClickButton: function(){
        var sels = jQuery(gridSelector).getGridParam("selarrrow")
        if ( ! sels.length) {
            alert("<?=$this->translate('Отметьте аттрибуты для добавления')?>");
            return false;
        }
        jQuery("#<?=$dlgAddToNew?>").data("grid", jQuery(gridSelector));
        viewModal("#<?=$dlgAddToNew?>", {gbox: "#gbox_"+gridId, jqm:true, jqM: true});
        return false;
    }
})
.navButtonAdd(pagerSelector, {
    caption: "",
    title: "<?=$this->translate('Использовать шаблонные аттрибуты')?>",
    buttonicon: "ui-icon-folder-open",
    onClickButton: function(){
        jQuery("#<?=$dlgGetFrom?>").data("grid", jQuery(gridSelector));
        viewModal("#<?=$dlgGetFrom?>", {gbox: "#gbox_"+gridId, jqm:true, jqM: true});
        return false;
    }
})
;

/****** get from attributes ********************************/
createModal(
    {
        themodal: "<?=$dlgGetFrom?>",
        modalhead: "<?=$dlgGetFrom?>_head",
        modalcontent: "<?=$dlgGetFrom?>_content",
        scrollelm: "<?=$dlgGetFrom?>_scroll"
    },
    <?=$contGetFrom?>,
    {
        caption: "<?=$this->translate('Выберите аттрибуты')?>",
        top : 0,left: 0,width: 300,height: 'auto',dataheight: 'auto',
        modal: true,jqModal : true,
        drag: true,resize: true,url: null,mtype : "POST",
        clearAfterAdd :true,closeAfterEdit : false,reloadAfterSubmit : true,
        onInitializeForm: null,beforeInitData: null,beforeShowForm: null,afterShowForm: null,
        beforeSubmit: null,afterSubmit: null,onclickSubmit: null,afterComplete: null,
        onclickPgButtons : null,afterclickPgButtons: null, editData : {},
        recreateForm : false,closeOnEscape : false,
        addedrow : "first",topinfo : '',bottominfo: '',
        saveicon : [],closeicon : [], savekey: [false,13],navkeys: [false,38,40],
        checkOnSubmit : false,checkOnUpdate : false,
        _savedData : {},processing : false,
        onClose : function(){hideModal("#<?=$dlgGetFrom?>");},
        ajaxEditOptions : {},serializeEditData : null,viewPagerButtons : true,
        gbox: "#gbox_"+gridId
    },
    "#gview_"+gridId,
    jQuery("#gview_"+gridId)[0],
    true
);


/********* on submit ***************/
jQuery("#<?=$dlgGetFrom?> .btn_submit").click(function(e){
    e.preventDefault();
    var $this = jQuery("#<?=$dlgGetFrom?>");
    var grid = $this.data("grid");
    var postData = "";
    $("#<?=$dlgGetFrom?> a.checked").each(function(){
        var $a = jQuery(this);
        var $v = jQuery("#<?=$dlgGetFrom?> .treeNodeInput[rowId="+$a.attr("rowId")+"]");
        postData += "&"+$a.attr("rowName")+"="+$a.attr("rowId")+"&"+$v.attr("name")+"="+$v.val();
    });
    jQuery.get("<?=$this->urlGetFromGroups?>", postData, function(res){
        if (res=="ok") {
            hideModal("#<?=$dlgGetFrom?>");
            grid.trigger("reloadGrid");
        }
        else {
            alert("<?=$this->translate('Ошибка')?>: "+res);
        }
    });
});
/********* on cancel ***************/
jQuery("#<?=$dlgGetFrom?> .btn_cancel").click(function(e){
    e.preventDefault();
    hideModal("#<?=$dlgGetFrom?>");
});




/***********************add to exist group ************************/


createModal(
    {
        themodal: "<?=$dlgAddToExist?>",
        modalhead: "<?=$dlgAddToExist?>_head",
        modalcontent: "<?=$dlgAddToExist?>_content",
        scrollelm: "<?=$dlgAddToExist?>_scroll"
    },
    <?=$contAddToExist?>,
    {
        caption: "<?=$this->translate('Выберите наборы')?>",
        top : 0,left: 0,width: 300,height: 'auto',dataheight: 'auto',
        modal: true,jqModal : true,
        drag: true,resize: true,url: null,mtype : "POST",
        clearAfterAdd :true,closeAfterEdit : false,reloadAfterSubmit : true,
        onInitializeForm: null,beforeInitData: null,beforeShowForm: null,afterShowForm: null,
        beforeSubmit: null,afterSubmit: null,onclickSubmit: null,afterComplete: null,
        onclickPgButtons : null,afterclickPgButtons: null, editData : {},
        recreateForm : false,closeOnEscape : false,
        addedrow : "first",topinfo : '',bottominfo: '',
        saveicon : [],closeicon : [], savekey: [false,13],navkeys: [false,38,40],
        checkOnSubmit : false,checkOnUpdate : false,
        _savedData : {},processing : false,
        onClose : function(){hideModal("#<?=$dlgAddToExist?>");},
        ajaxEditOptions : {},serializeEditData : null,viewPagerButtons : true,
        gbox: "#gbox_"+gridId
    },
    "#gview_"+gridId,
    jQuery("#gview_"+gridId)[0],
    true
);

/********* on submit ***************/
jQuery("#<?=$dlgAddToExist?> .btn_submit").click(function(e){
    e.preventDefault();
    var $this = jQuery("#<?=$dlgAddToExist?>");
    var grid = $this.data("grid");
    var postData = "";
    $("#<?=$dlgAddToExist?> a.checked").each(function(){
        var $a = jQuery(this);
        postData += "&"+$a.attr("rowName")+"="+$a.attr("rowId");
    });
    var sels = jQuery(gridSelector).getGridParam("selarrrow");
    for (i in sels) {
        postData += "&rows[]="+sels[i];
    }
    jQuery.get("<?=$this->urlAddToExistGroups?>", postData, function(res){
        if (res=="ok") {
                    jQuery.get("<?=$this->urlGetGroups?>", {type: "tree_with_attributes"}, function(treeHtml){
                        $("#<?=$dlgGetFrom?> #attributes_from_groups").replaceWith(treeHtml);
                        hideModal("#<?=$dlgAddToExist?>");
                        grid.trigger("reloadGrid");
                    });
        }
        else {
            alert("<?=$this->translate('Ошибка')?>: "+res);
        }
    });
});
/********* on cancel ***************/
jQuery("#<?=$dlgAddToExist?> .btn_cancel").click(function(e){
    e.preventDefault();
    hideModal("#<?=$dlgAddToExist?>");
});


/***********************add to new group ************************/


createModal(
    {
        themodal: "<?=$dlgAddToNew?>",
        modalhead: "<?=$dlgAddToNew?>_head",
        modalcontent: "<?=$dlgAddToNew?>_content",
        scrollelm: "<?=$dlgAddToNew?>_scroll"
    },
    <?=$contAddToNew?>,
    {
        caption: "<?=$this->translate('Новый набор атрибутов')?>",
        top : 0,left: 0,width: 300,height: 'auto',dataheight: 'auto',
        modal: true,jqModal : true,
        drag: true,resize: true,url: null,mtype : "POST",
        clearAfterAdd :true,closeAfterEdit : false,reloadAfterSubmit : true,
        onInitializeForm: null,beforeInitData: null,beforeShowForm: null,afterShowForm: null,
        beforeSubmit: null,afterSubmit: null,onclickSubmit: null,afterComplete: null,
        onclickPgButtons : null,afterclickPgButtons: null, editData : {},
        recreateForm : false,closeOnEscape : false,
        addedrow : "first",topinfo : '',bottominfo: '',
        saveicon : [],closeicon : [], savekey: [false,13],navkeys: [false,38,40],
        checkOnSubmit : false,checkOnUpdate : false,
        _savedData : {},processing : false,
        onClose : function(){hideModal("#<?=$dlgAddToNew?>");},
        ajaxEditOptions : {},serializeEditData : null,viewPagerButtons : true,
        gbox: "#gbox_"+gridId
    },
    "#gview_"+gridId,
    jQuery("#gview_"+gridId)[0],
    true
);

/********* on submit ***************/
jQuery("#<?=$dlgAddToNew?> .btn_submit").click(function(e){
    e.preventDefault();
    var $this = jQuery("#<?=$dlgAddToNew?>");
    var grid = $this.data("grid");
    var postData = "";
    $("#<?=$dlgAddToNew?> *:input").each(function(){
        var $inp = jQuery(this);
        postData += "&"+$inp.attr("name")+"="+$inp.val();
    });
    var sels = jQuery(gridSelector).getGridParam("selarrrow");
    for (i in sels) {
        postData += "&rows[]="+sels[i];
    }
    jQuery.get("<?=$this->urlAddToNewGroup?>", postData, function(res){
        if (res=="ok") {
            jQuery.get("<?=$this->urlGetGroups?>", {type: "tree"}, function(treeHtml){
                $("#<?=$dlgAddToExist?> #groups").replaceWith(treeHtml);
                jQuery.get("<?=$this->urlGetGroups?>", {type: "select"}, function(selHtml){
                    $("#<?=$dlgAddToNew?> #parent_id").replaceWith(selHtml);
                    jQuery.get("<?=$this->urlGetGroups?>", {type: "tree_with_attributes"}, function(treeHtml){
                        $("#<?=$dlgGetFrom?> #attributes_from_groups").replaceWith(treeHtml);
                        hideModal("#<?=$dlgAddToNew?>");
                        grid.trigger("reloadGrid");
                    });
                });
            });
        }
        else {
            alert("<?=$this->translate('Ошибка')?>: "+res);
        }
    });
});
/********* on cancel ***************/
jQuery("#<?=$dlgAddToNew?> .btn_cancel").click(function(e){
    e.preventDefault();
    hideModal("#<?=$dlgAddToNew?>");
});

