[
    {index:"code", name:"code", hidden:true, width:"50",  sortable:true, align:"left", editable:true },
    {index:"status", name:"status", width:"75",  sortable:false, align:"center",
        editable:true, edittype:"select", editoptions: {value:<?=$this->statusOptionsJson?>} },
    {index:"type",   name:"type",   width:"75",  sortable:false, align:"center",
        editable:true, edittype:"select", editoptions: {value:<?=$this->typeOptionsJson?>} },
    {index:"name", name:"name", width:"100", sortable:true, align:"left", editable:true },
    {index:"current_value", name:"current_value", width:"100", sortable:true, align:"left", editable:true, edittype:"custom", editoptions:{
        /*custom_element:attributesInitCurrentValue*/
        custom_element:function(value, options) {
            var el;
            var $this = jQuery("#attributes");
            var suffix = "_"+options.name;
            var id = options.id.substr(0, options.id.length-suffix.length);
            var rowData = $this.getRowData(id);
            var typeEl = jQuery("#"+id+"_type");
            var rowType;
            if (typeEl.length) {
                rowType = typeEl.val();
            }
            else {
                rowType = rowData.type;
            }

            /* int/dec/str types attribute */
            if ((rowType == "int") || (rowType == "decimal") || (rowType == "string")) {
                var el = jQuery("<input type=\"text\" />");
                jQuery(el).val(value);
                return el;
            }
            /* datetime type attribute */
            else if (rowType == "datetime") {
                var el = jQuery("<input type=\"text\" />");
                jQuery(el).val(value);
                return el;
            }
            /* text type attribute */
            else if (rowType == "text") {
                var el = jQuery("<textarea></textarea>");
                jQuery(el).html(value);
                return el;
            }
            /* variant type attribute */
            else if (rowType == "variant") {
                preOpts = rowData.variants_text.split("|");
                opts = {"":"--"};
                for (i in preOpts) {
                    kv = preOpts[i].split(";");
                    opts[kv[0]] = kv[0];
                }
                var html = "<select>";
                var selected = "";
                for (val in opts) {
                    if (value==val) {
                        selected="selected=\"selected\"";
                    }
                    else {
                        selected = "";
                    }
                    html += "<option "+selected+" value=\""+val+"\">"+opts[val]+"</option>";
                }
                html += "</select>";
                el = jQuery(html);
                return el;
            }
            else {
                el = document.createElement("input");
                el.type="text";
                el.value = value;
            }
            return el;
        },
        /*custom_value:attributesGetCurrentValue*/
        custom_value:function(elem) {
            return jQuery(elem).val();
        }
    } },
    {index:"variants_text", name:"variants_text", hidden:true, width:"150", align:"left", editable:true, edittype:"textarea" },
    {index:"param1", name:"param1", width:"50", sortable:true, align:"right", editable:true },
    {index:"param2", name:"param2", width:"50", sortable:true, align:"right", editable:true }

]