function(id){
      var $this = jQuery(this);
      if(id){
        $this.saveRow($this.data("lastsel2"));
        $this.collapseSubGridRow(id);
        $this.editRow(id,true, function(id){
            var rowData = $this.getRowData(id);
            var typeEl = jQuery("#"+id+"_type");
            var rowType;
            if (typeEl.length) {
                rowType = typeEl.val();
            }
            else {
                rowType = rowData.type;
            }
            if (rowType == "datetime") {
                jQuery("#"+id+"_current_value").datepicker({
                    showStatus: true,
                    showOn: "both",
                    showTime: true,
                    constrainInput: true,
                    buttonImage: "<?=$this->skin()->url()?>images/calendar.png",
                    buttonImageOnly: true,
                    dateFormat: "yy-mm-dd",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "1920:2020"
                });
            }
        });
        $this.data("lastsel2", id);
      }
}
