<? $this->pageTitle($this->translate('Pages list')); ?>

<?=$this->adminMassForm('formStart')?>
<div class="widget-box collapsible">
    <div class="widget-title">
        <a href="#collapseThree" data-toggle="collapse">
			<span class="icon"><i class="icon-pencil"></i></span>
                <h5><?=$this->translate('Действия со страницами')?></h5>
        </a>
    </div>
    <div class="collapse" id="collapseThree">
        <div class="widget-content">
                <?=$this->adminMassForm('actions')?>
        </div>
    </div>
</div>

<div class="widget-box table">
    <div class="widget-title"><h5><?=$this->translate('Список страниц')?></h5>
    <div class="buttons">
        <a href="<?=$this->stdUrl(array('reset'=>TRUE), 'edit', 'admin-page')?>" class="btn btn-mini">
        <i class="icon-file"></i>
        <?=$this->translate('New')?>
        </a>      
    </div>
    </div>
    <div class="widget-content nopadding">  
<? $i = 0 ?>

    <table cellspacing="0" class="table table-bordered table-striped table-hover table-no-external-border">
      <tr>
        <th width="50px"><?=$this->adminMassForm('checkAll')?></th>
        <th width="12%"><?=$this->translate('Sorting')?></th>
        <th><?=$this->translate('Page title')?></th>
        <th><?=$this->translate('Seo id')?></th>
        <th><?=$this->translate('Внутр. код')?></th>
        <th class="actions2" width="12%"><?=$this->translate('Actions')?></th>
      </tr>

<? foreach ($this->pages as $row) { ?>
      <tr >
        <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
        <td> <?=$this->adminListSorting(array('id'=>$row['id'], 'action'=>'sorting'))?></td>
        <td <?=( ! (int) $row['status'])?'style="font-style:italic;"':''?>> <?=$row['title']?> </td>
        <td> <?=$row['seo_id']?></td>
        <td> <?=$row['code']?></td>
        <td class="actions2">
            <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit')?>"><?=$this->translate('Edit')?></a>
             /
            <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete')?>"><?=$this->translate('Delete')?></a>
        </td>
      </tr>

    <? ++$i ?>
<? } ?>


    </table>

</div>
    <?=$this->paginationControl($this->pages)?>
    <?=$this->adminMassForm('formEnd')?>
</div>

