<h2><?=$this->translate('Список "белых" IP')?></h2>

<?=$this->adminMassForm('formStart')?>
<?=$this->adminMassForm()->setMassActions(array('delete'))->adminMassForm('actions')?>

<? $i = 0 ?>

    <table cellspacing="0" class="tbl">
      <tr>
        <th width="15%"><?=$this->adminMassForm('checkAll')?></th>
        <th width="30%"><?=$this->translate('IP-адрес')?></th>
        <th><?=$this->translate('Имя сети')?></th>
        <th class="actions2"><?=$this->translate('Actions')?></th>
      </tr>

<? foreach ($this->ips as $row) { ?>
      <tr >
        <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
        <td><?=$row['ip']?></td>
        <td><?=$row['provider']?></td>
        <td class="actions2">
            <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit')?>"><?=$this->translate('Edit')?></a>
             /
            <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete')?>"><?=$this->translate('Delete')?></a>
        </td>
      </tr>

    <? ++$i ?>
<? } ?>


    </table>


    <?=$this->adminMassForm('formEnd')?>

    <?=$this->paginationControl($this->ips)?>


  <a href="<?=$this->stdUrl(array('reset'=>TRUE), 'edit', 'admin-white-ip')?>" class="btn2"><?=$this->translate('Добавить')?></a>

