<div class="user_body">
	<div class="user_top">
    	<div class="user_bank">
    		<p class="user_bank_p">Банк получателя</p>
            <p class="user_bank_name"><?=$this->payment->seller_requisites['bank']?></p>
    	</div>
        <div class="user_bank_content">
        	<p>БИК		<?=$this->payment->seller_requisites['bik']?></p>
            <p>Сч. №	<?=$this->payment->seller_requisites['rs']?></p>
        </div>
    </div>
    <div class="user_separator">
    	<div class="user_bottom">
        	<div class="user_left">
            	<div class="user_data">
                	<div>ИНН	<?=$this->payment->seller_requisites['inn']?></div>
                    <div>КПП	<?=$this->payment->seller_requisites['kpp']?></div>
                </div>
            	<div class="user_left_separator">
                    <p class="user_info">Получатель</p>
                    <p class="user_bank_name"><?=$this->payment->seller_requisites['name']?></p>
                </div>
            </div>
            <div class="user_right">
            	<p>Сч. №	<?=$this->payment->seller_requisites['ks']?></p>
            </div>
        </div>
    </div>
</div>
