			<h1><?=$this->translate('Отмена заказа')?></h1>
	        <div><img src="<?=$this->skin()->url()?>images/body/white-box-top-bg.png" width="746" height="10" border="0" /></div>
	        <div class="white-box-y vnutr basket">
				<div class="padd">
<? if ($this->cancelled !== TRUE) { ?>
    <h3><?=$this->translate('Вы действительно хотите отменить заказ')?> ?</h3>
    <?=$this->renderForm($this->form, 'front_form.phtml')?>    		
<? } else { ?>
    <h3><?=$this->translate('Заказ отменен')?></h3>
<? } ?>
    			</div>
    		</div>
			<div class="tag-bott-25"><img src="<?=$this->skin()->url()?>images/body/white-box-bott-bg.png" width="746" height="10" border="0" /></div>
