<?/*?>
<div class="text_page">
  <h2><?=$this->translate('Заказ')?></h2>
  <form name="order" method="POST">
  <div class="basket_wrapp">
    <table cellspacing="0" class="basket">
      <tr>
        <th scope="col"><?=$this->translate('Товар')?></th>
        <th scope="col"><?=$this->translate('Количество')?></th>
        <th scope="col"><?=$this->translate('Цена за единицу')?></th>
        <th scope="col"><?=$this->translate('Стоимость')?></th>
      </tr>
    <? $i = 0 ?>
    <? foreach ($this->order->items as $item) { ?>
      <tr>
        <td>
            <input type="hidden" name="hash[<?=$item['hash']?>]" value="<?=$item['hash']?>" />
             <?=$item['name']?> <?=$item['attributes_html']?>
        </td>
        <td class="qty"><?=$item['qty']?></td>
        <td class="price"><?=$this->order_Summ($item['price'])?></td>
        <td class="del"><?=$this->order_Summ($item['price'] * $item['qty'])?></td>
      </tr>
    <? } ?>
    </table>
    <?=$this->order_Total($this->order)?>
    <div class="buttons">
        <span class="r_align">
            <a href="#" onclick="document.order.submit();return false;"><img src="<?=$this->skin()->url()?>images/btn/checkout.gif" alt="" width="113" height="21" border="0" class="btn" /></a>
        </span>
    </div>
  </div>
  </form>
</div>
<?*/?>

		  <h1><?=$this->translate('Заказ')?></h1>
	        <div><img src="<?=$this->skin()->url()?>images/body/white-box-top-bg.png" width="746" height="10" border="0" /></div>
	        <form name="order" method="POST">
	        <div class="white-box-y vnutr basket">
				<div class="padd">
				  <div id="header-bs" >
				  	<div class="count"><?=$this->translate('Количество')?>:</div>
					<div class="price"><?=$this->translate('Цена')?>:</div>
					<div class="title left"><?=$this->translate('Наименование')?>:</div>
					<div class="cleaner"></div>
				  </div>
		    <? $i = 0 ?>
		    <? foreach ($this->order->items as $item) { ?>
				<div class="row">
				  	<div class="count"><?=$item['qty']?></div>
					<div class="price"><?=$this->order_Summ($item['price'], $this->order->currency)?></div>
					<div class="title left"><a href="<?=$this->url(array('seo_id'=>$item['seo_id']), 'item')?>"><?=$item['name']?></a><br><?=$item['attributes_html']?></a></div>
					<div class="cleaner"></div>
				</div>
			<? } ?>
				<div class="footer">
					<?=$this->order_Total($this->order, TRUE, FALSE, 'shop')?>
					
				  
				  <div class="buttons">
					<div class="box-basket"><a href="#" class="basket-submit" onclick="document.order.submit();return false;"><?=$this->translate('Подтвердить')?></a></div>
					<div class="box-basket"><a href="<?=$this->stdUrl(array('reset' => TRUE), 'cancel', 'order', 'checkout')?>" class="basket-submit"><?=$this->translate('Отменить')?></a></div>
				</div>
				</div>
			</div>
				<div class="cleaner"></div>
		    </div>
		    </form>
            <div class="tag-bott-25"><img src="<?=$this->skin()->url()?>images/body/white-box-bott-bg.png" width="746" height="10" border="0" /></div>
