
    <h1><?=$this->translate('Заказ оформлен')?></h1>
	        <div><img src="<?=$this->skin()->url()?>images/body/white-box-top-bg.png" width="746" height="10" border="0" /></div>
	        <div class="white-box-y vnutr basket">
				<div class="padd">

		<h3><?=$this->translate('Благодарим Вас за покупку')?>!</h3>
        <a target="_blank" href="<?=$this->stdUrl(NULL, 'print', 'order', 'checkout')?>">Распечатать счет</a>

				</div>
			</div>

	<div class="tag-bott-25"><img src="<?=$this->skin()->url()?>images/body/white-box-bott-bg.png" width="746" height="10" border="0" /></div>

