<h1><?=$this->translate('Заказ #%1$s', $this->order->id)?></h1>
<table width="100%" cellpadding="0" cellspacing="0" border="1">
    <tr>
        <th><?=$this->translate('#')?></th>
        <th><?=$this->translate('Товар')?></th>
        <th><?=$this->translate('Кол-во')?></th>
        <th><?=$this->translate('Цена за ед.')?></th>
        <th><?=$this->translate('Ст-сть')?></th>
    </tr>
    <? $i = 0 ?>
    <? foreach ($this->order->items as $item) { ?>
        <tr>
            <td>
                <?=( ++ $i)?>
            </td>
            <td>
                <h4><?=$item['name']?></h4>
                <?=$item['attributes_html']?>
            </td>
            <td>
                <?=$item['qty']?>
            </td>
            <td><?=$this->order_Summ($item['price'], $this->order->currency)?></td>
            <td><?=$this->order_Summ( (float) $item['price'] * (float) $item['qty'], $this->order->currency)?></td>
        </tr>
    <? } ?>
</table>
<?=$this->order_Total($this->order, TRUE, TRUE)?>
