<h1>Пользователь <?=$this->issue->adder_name?> добавил для Вас задачу</h1>
<ul>
    <li><strong>Тема:</strong> <?=$this->issue->subject?> </li>
    <li><strong>Срок выполнения:</strong> <?=$this->issue->date_due?> </li>
    <li><strong>Задача</strong> <?=$this->issue->text?></li>
</ul>
<p>Данное сообщение создано автоматически, отвечать на это письмо не обязательно.<p>
<p>Администрация сайта <?=$this->config->www->siteName?></p>


