<h2><?=$this->translate('FAQs list')?></h2>

<?=$this->filter?>

<?=$this->adminMassForm('formStart')?>
<?=$this->adminMassForm('actions')?>

<? $i = 0 ?>

    <table cellspacing="0" class="tbl">
      <tr>
        <th><?=$this->adminMassForm('checkAll')?></th>
        <th><?=$this->translate('Sorting')?></th>
        <th><?=$this->translate('Question')?></th>
        <th><?=$this->translate('Seo id')?></th>
        <th class="actions2"><?=$this->translate('Actions')?></th>
      </tr>

<? foreach ($this->faqs as $row) { ?>
      <tr >
        <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
        <td> <?=$this->adminListSorting(array('id'=>$row['id'], 'action'=>'sorting'))?></td>
        <td> <?=$row['quest']?> </td>
        <td> <?=$row['seo_id']?></td>
        <td class="actions2">
            <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit')?>"><?=$this->translate('Edit')?></a>
             /
            <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete')?>"><?=$this->translate('Delete')?></a>
        </td>
      </tr>

    <? ++$i ?>
<? } ?>


    </table>


    <?=$this->adminMassForm('formEnd')?>

    <?=$this->paginationControl($this->faqs)?>


  <a href="<?=$this->stdUrl(array('reset'=>TRUE), 'edit', 'admin-faq')?>" class="btn2"><?=$this->translate('New')?></a>

