<? $this->pageTitle($this->translate('Баннеры')); ?>
<?=$this->adminMassForm('formStart')?>
<div class="widget-box collapsible">
    <div class="widget-title">
        <a href="#collapseThree" data-toggle="collapse">
			<span class="icon"><i class="icon-pencil"></i></span>
                <h5><?=$this->translate('Действия с баннерами')?></h5>
        </a>
    </div>
    <div class="collapse" id="collapseThree">
        <div class="widget-content">
                <?=$this->adminMassForm('actions', $this->massActionsConfig)?>
        </div>
    </div>
</div>

<div class="widget-box table">
    <div class="widget-title"><h5><?=$this->translate('Список баннеров')?></h5>
    <div class="buttons">
        <a href="<?=$this->stdUrl(array('reset'=>TRUE), 'edit', 'admin-banner')?>" class="btn btn-mini">
        <i class="icon-file"></i>
        <?=$this->translate('New')?>
        </a>      
    </div>
    </div>
    <div class="widget-content nopadding">  

<? $i = 0 ?>

     <table cellspacing="0" class="table table-bordered table-striped table-hover table-no-external-border">
      <tr>
        <th width="50px"><?=$this->adminMassForm('checkAll')?></th>
        <th width="12%"><?=$this->translate('Sorting')?></th>
        <th><?=$this->translate('Name')?></th>
        <th><?=$this->translate('Place')?></th>
        <th><?=$this->translate('Status')?></th>
        <th class="actions2"><?=$this->translate('Actions')?></th>
      </tr>

 <? $config = Zend_Registry::get('config')?>
<? foreach ($this->banners as $row) { ?>
      <tr >
        <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
        <td> <?=$this->adminListSorting(array('id'=>$row['id'], 'action'=>'sorting'))?></td>
        <td><?=$row['name']?></td>
        <td> <?=$this->translate($row['place']) . ' /'.$config->banners->{$row['place']}?> </td>
        <td align="center">
            <?=$row['status']=='1'?$this->translate('вкл.'):$this->translate('выкл.')?>
        </td>
        <td class="actions2" width="12%">
            <!--a class="btn btn-inverse btn-mini" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit')?>"><i class="icon-pencil icon-white"></i></a>
            <a class="btn btn-inverse btn-mini" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete')?>"><i class="icon-remove icon-white"></i></a-->
            <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit')?>"><?=$this->translate('Edit')?></a>
             /
            <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete')?>"><?=$this->translate('Delete')?></a>
        </td>
      </tr>

    <? ++$i ?>
<? } ?>


    </table>
</div>
    <?=$this->paginationControl($this->banners)?>
    <?=$this->adminMassForm('formEnd')?>    
</div>
