
<?
    $this->headScript('FILE', $this->stdUrl(array('reset'=>TRUE)).'js/jquery/jquery-ui.js');
    $this->headLink(array('type' => 'text/css','rel' => 'stylesheet','href' => $this->stdUrl(array('reset'=>TRUE)) . 'js/jquery/theme/ui.core.css'));
    $this->headLink(array('type' => 'text/css','rel' => 'stylesheet','href' => $this->stdUrl(array('reset'=>TRUE)) . 'js/jquery/theme/ui.theme.css'));
    $this->headLink(array('rel' => 'stylesheet','type' => 'text/css',
                          'href' => $this->stdUrl(array('reset'=>TRUE)).'js/jquery/theme/ui.dialog.css'));
    $this->headLink(array('rel' => 'stylesheet','type' => 'text/css',
                          'href' => $this->stdUrl(array('reset'=>TRUE)).'js/jquery/theme/jquery-ui-lightness.css'));
?>


<? $this->headScript('SCRIPT', '

    function issue_InitDialog(dialogId, responseFunc) {
        var div = $("#"+dialogId+"");
        div.dialog({
            autoOpen: false,
            closeOnEscape: true,
            width: 600,
            height: 340,
            buttons: {
                "'.$this->translate('Ok').'": function () {
                    var $this = $(this);
                    var issueId = $this.data("issueId");
                    var url = $this.data("url");
                    var data = $(":input", this).serializeArray();
                    var postData = {};
                    for (el in data) {
                        postData[data[el].name] = data[el].value;
                    }
                    postData.issueId = issueId;
                    $.post(url, postData, function(res){
                        responseFunc(res);
                        $("body").trigger("dialog_"+$this.attr("id")+"__afterSubmit");
                        $this.dialog("close");
                    }, "json");
                },
                "'.$this->translate('Cancel').'": function () {
                    $(this).dialog("close");
                },
            }
        });
    }

')?>






<? $chsDialogId = $this->dialogId ?>
<? $this->headScript('SCRIPT', '

    $(function(){
        $("body").append('.Zend_Json::encode('<div id="'.$chsDialogId.'" style="display: none" dlgWidth="500" dlgHeight="300">'.$this->renderForm($this->changeStatusForm).'</div>').');

        issue_InitDialog("'.$chsDialogId.'", function(res){
            /* set value for status */
            var spanStatus = $("span.'.$this->statusClass.'[issueId="+res.issueId+"]");
            spanStatus.attr("status", res.status.value);
            spanStatus.html(res.status.text);
            /* set value for date_due */
            var spanDateDue = $("span.'.$this->dateDueClass.'[issueId="+res.issueId+"]");
            spanDateDue.attr("dateDue", res.date_due.value);
            spanDateDue.html(res.date_due.text);
        });

        $("a.'.$this->linkClass.'").click(function(e){
            e.preventDefault();
            var $this = $(this);
            var issueId =  $this.attr("issueId");
            $("#'.$chsDialogId.' form")[0].reset();
            var status = $("span.'.$this->statusClass.'[issueId="+issueId+"]").attr("status");
            var dateDue = $("span.'.$this->dateDueClass.'[issueId="+issueId+"]").attr("dateDue");
            $("#'.$chsDialogId.' select#'.$this->statusField.'").val(status);
            $("#'.$chsDialogId.' input#'.$this->dateDueField.'").val(dateDue);
            $("#'.$chsDialogId.'").data("issueId", issueId)
            $("#'.$chsDialogId.'").data("url", $this.attr("href"))
            $("#'.$chsDialogId.'").dialog("open");
        });
    });
')?>

<? $this->jquery_Datepicker($this->dateDueField)?>

