<table cellpadding="0" cellspacing="0" class="issue_subtable">
    <? foreach ($this->history as $row) { ?>
    <tr>
        <td width="25%"><?=$this->formatDate($row['date'], TRUE)?></td>
        <td width="20%"><a href="<?=$this->url(array('login'=>$row['user']['login']), 'user_profile')?>"><?=$row['user']['name']?></a></td>
        <td width="20%"><?=$this->issue_Status($row['status'])?></td>
        <td width="35%"><?=$this->issue_Comment($row)?></td>
    </tr>
    <? } ?>
</table>
