<select id="<?=$this->formId?>_select" name="mass_action" style="width: 250px">
    <? foreach ($this->params['options'] as $value=>$text) { ?>
        <option value="<?=$value?>"><?=$text?></option>
    <? } ?>
</select>

<script type="text/javascript">
    $(document).ready(function(){
        $('#<?=$this->formId?>_select').bind('change', function(){
            if ($("input.mass-form-check:checked").length > 0) {
                if (confirm('<?=$this->translate('Do you confirm this action for all selected items')?>?')) {
                    this.form.submit();
                }
                else {
                    $(this).val('');
                }
            }
            else {
                alert('<?=$this->translate('Nothing selected')?>');
                $(this).val('');
            }
        });
    });
</script>
