

<? $errors = array_merge($this->form->getErrors(), $this->form->getErrorMessages()) ?>

<form  enctype="multipart/form-data"
    <? foreach ($this->form->getAttribs() as $name=>$value) { ?>
        <?=$name?>="<?=$value?>"
    <? } ?>
>


<table class="frm">

<? $buttons = array() ?>
<? $hiddens = array() ?>
<? foreach ($this->form->getElements() as $el) {?>
    <? if (($el instanceof Zend_Form_Element_Submit) OR ($el instanceof Zend_Form_Element_Button)) { ?>
        <? $buttons[]=$el ?>
    <? } else if ($el instanceof Zend_Form_Element_Hidden) { ?>
        <? $hiddens[]=$el ?>
    <? } else { ?>
        <tr>
            <td class="label"><label for="<?=$el->getName()?>"><?=$el->getLabel()?><? if ($el->isRequired()) {?> <?=$this->formMarkerRequired()?><? } ?> :</label></td>
            <td class="value">
                <? if ($errors[$el->getName()]) { ?>
                    <div class="red" style="color:red">
                    <?=$this->form->getElementErrorsFormatted($el->getName(), $errors[$el->getName()])?>
                    </div>
                <? } ?>
                <?/* if (in_array($el->getType(), array('Zend_Form_Element_Text', 'Zend_Form_Element_Password'))) { ?>
                        <? $el->setAttrib('class', 'input') ?>
                <? } else if ($el->getType() == 'Zend_Form_Element_Select') { ?>
                        <? $el->setAttrib('class', 'select') ?>
                <? } else if ($el->getType() == 'Zend_Form_Element_Textarea') { ?>
                        <? $el->setAttrib('class', 'textarea') ?>
                <? } */?>
                <? $el->setDecorators(array('ViewHelper')) ?>
                <?=$el->render()?>
            </td>
        </tr>
    <? } ?>
<? } ?>


</table>
<div class="cleaner">&nbsp;</div>
<div class="cleaner">&nbsp;</div>

    <? if (count($buttons)) { ?>
        <div style="text-align: center; width: 100%">
            <table align="center"><tr>
            <? foreach ($buttons as $btn) {?>
                <td><?=$btn->render()?></td>
            <? } ?>
            </tr></table>
        </div>
    <? } ?>
<? foreach ($hiddens as $el) { ?><?=$el->render()?><? } ?>

</form>

