<? $this->pageTitle($this->translate('News topics list')); ?>
<?=$this->adminMassForm('formStart')?>
<div class="widget-box collapsible">
    <div class="widget-title">
        <a href="#collapseThree" data-toggle="collapse">
			<span class="icon"><i class="icon-pencil"></i></span>
                <h5><?=$this->translate('Действия с рубриками')?></h5>
        </a>
    </div>
    <div class="collapse" id="collapseThree">
        <div class="widget-content">
                <?=$this->adminMassForm('actions')?>
        </div>
    </div>
</div>

<div class="widget-box table">
    <div class="widget-title"><h5><?=$this->translate('Список рубрик')?></h5>
    <div class="buttons">
        <a href="<?=$this->stdUrl(array('reset'=>TRUE), 'edit', 'admin-news-topic')?>" class="btn btn-mini">
        <i class="icon-file"></i>
        <?=$this->translate('New')?>
        </a>      
    </div>
    </div>
    <div class="widget-content nopadding">  
<? $i = 0 ?>

    <table cellspacing="0" class="table table-bordered table-striped table-hover table-no-external-border">
      <tr>
        <th width="50px"><?=$this->adminMassForm('checkAll')?></th>
        <?/*?><th><?=$this->translate('Sort')?></th><?*/?>
        <th><?=$this->translate('Title')?></th>
        <th class="actions2" width="12%"><?=$this->translate('Actions')?></th>
      </tr>

<? foreach ($this->topics as $row) { ?>
      <tr >
        <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
        <?/*?><td> <?=$this->adminListSorting(array('id'=>$row['id'], 'action'=>'sorting'))?></td><?*/?>
        <td> <?=$row['name']?> <?=$row['news_count']?'('.$row['news_count'].')':''?></td>
        <td class="actions2">
            <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit')?>"><?=$this->translate('Edit')?></a>
             /
            <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete')?>"><?=$this->translate('Delete')?></a>
        </td>
      </tr>

    <? ++$i ?>
<? } ?>


    </table>

</div>
    <?=$this->adminMassForm('formEnd')?>

    <?=$this->paginationControl($this->topics)?>

</div>

