<? $this->pageTitle($this->translate('Roles list')); ?>
<?=$this->filter?>

<?=$this->adminMassForm('formStart')?>
<div class="widget-box collapsible">
    <div class="widget-title">
        <a href="#collapseThree" data-toggle="collapse">
			<span class="icon"><i class="icon-pencil"></i></span>
                <h5><?=$this->translate('Действия с группами')?></h5>
        </a>
    </div>
    <div class="collapse" id="collapseThree">
        <div class="widget-content">
                <?=$this->adminMassForm('actions')?>
        </div>
    </div>
</div>
<div class="widget-box table">
    <div class="widget-title"><h5><?=$this->translate('Список групп')?></h5>
    <div class="buttons">
        <a href="<?=$this->stdUrl(array('reset'=>TRUE), 'edit', 'admin-role')?>" class="btn btn-mini">
        <i class="icon-file"></i>
        <?=$this->translate('New')?>
        </a>        
    </div>
    </div>
    <div class="widget-content nopadding"> 
<? $i = 0 ?>

    <table cellspacing="0" class="table table-bordered table-striped table-hover table-no-external-border">
      <tr>
        <th width="50px"><?=$this->adminMassForm('checkAll')?></th>
        <th width="12%"><?=$this->translate('Sorting')?></th>
        <th><?=$this->translate('Image')?></th>
        <th><?=$this->translate('Role name')?></th>
        <th><?=$this->translate('Acl role')?></th>
        <th class="actions2" width="12%"><?=$this->translate('Actions')?></th>
      </tr>

<? foreach ($this->roles as $row) { ?>
      <tr >
        <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
        <td> <?=$this->adminListSorting(array('id'=>$row['id'], 'action'=>'sorting'))?></td>
        <td>
            <? if ($row['rc_id']) { ?>
                <img src="<?=App_Resource::getUploadsUrl($row['rc_id_preview'])?>">
            <? } ?>
        </td>
        <td><?=$row['name']?></td>
        <td><?=$row['acl_role']?></td>
        <td class="actions2">
            <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit')?>"><?=$this->translate('Edit')?></a>
             /
            <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete')?>"><?=$this->translate('Delete')?></a>
        </td>
      </tr>

    <? ++$i ?>
<? } ?>


    </table>

</div>
    <?=$this->paginationControl($this->roles)?>
    <?=$this->adminMassForm('formEnd')?>
</div>


