<h2><?=$this->translate('Цели и задачи')?></h2>

<?=$this->filter?>

<?/*=$this->adminMassForm('formStart')?>

<?=$this->adminMassForm('actions') */?>


<table width="100%" cellpadding="0" cellspacing="0">
<tr>
    <td align="right">
        <a class="btn2" href="<?=$this->stdUrl(array('id'=>NULL), 'edit', 'index', 'issues')?>"><?=$this->translate('New')?></a>
    </td>
</tr>
</table>

<? $i = 0 ?>

    <table cellspacing="0" class="tbl">
      <tr>
        <!-- th width="5%"><?=$this->adminMassForm('checkAll')?></th -->
        <th width="5%"><?=$this->translate('#')?></th>
        <th width="40%"><?=$this->translate('Тема')?></th>
        <th width="13%"><?=$this->translate('Состояние')?></th>
        <th><?=$this->translate('Добавлена')?></th>
        <th><?=$this->translate('Обновлена')?></th>
        <th><?=$this->translate('Конечный срок')?></th>
        <th  width="13%" class="actions"><?=$this->translate('Действия')?></th>
      </tr>


<? foreach ($this->issues as $row) { ?>
      <tr >
        <!-- td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td -->
        <td align="right"> <a href="<?=$this->stdUrl(array('id'=>$row['id']), 'issue', 'index', 'issues')?>"><?=$row['id']?></a> </td>
        <td> <a href="<?=$this->stdUrl(array('id'=>$row['id']), 'issue', 'index', 'issues')?>"><?=$row['subject']?></a> </td>
        <td> <span class="<?=$this->issue_ChangeStatusDialog()->getStatusClass()?>" issueId="<?=$row['id']?>" status="<?=$row['status']?>"><?=$this->issue_Status($row)?></span> </td>
        <td align="center"> <?=$this->formatDate($row['date_added'], TRUE)?> </td>
        <td align="center"> <?=$this->formatDate($row['date_changed'], TRUE)?> </td>
        <td align="center"> <span class="<?=$this->issue_ChangeStatusDialog()->getDateDueClass()?>" issueId="<?=$row['id']?>" dateDue="<?=$row['date_due']?>"><?=$this->formatDate($row['date_due'])?></span> </td>
        <td class="actions2">
            <? if ($row->isAllowedEdit) { ?>
                <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit')?>"><?=$this->translate('Правка')?></a>
                <?/*?>/
                <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete')?>"><?=$this->translate('Удалить')?></a><?*/?>
                <br/>
            <? } ?>
            <? if ($row->isAllowedChangeStatus) { ?>
                <a class="<?=$this->issue_ChangeStatusDialog()->getLinkClass()?>" href="<?=$this->stdUrl(NULL, 'ajax-change-status', 'index', 'issues')?>" issueId="<?=$row['id']?>"><?=$this->translate('Изменить статус/срок')?></a>
                <br/>
            <? } ?>
        </td>
      </tr>

    <? ++$i ?>
<? } ?>


    </table>


    <?/*=$this->adminMassForm('formEnd') */?>

    <?=$this->paginationControl($this->issues)?>

    <?=$this->issue_ChangeStatusDialog(TRUE)?>