  <h4><?=$this->translate('Задача  № %1$s', $this->issue->id)?></h4>

  <div class="cleaner"></div>

<!-- table width="100%" cellpadding="0" cellspacing="0">
<tr>
    <td>
    </td>
    <td width="15%" align="right">
        <? if ($this->issue->isAllowedEdit) { ?>
            <a class="btn3" href="<?=$this->stdUrl(array('id'=>$this->issue->id), 'edit')?>"><?=$this->translate('Правка')?></a>
        <? } ?>
    </td>
    <td width="15%" align="right">
        <? if ($this->issue->isAllowedChangeStatus) { ?>
            <a class="btn3 change-status-link" href="<?=$this->stdUrl(NULL, 'ajax-change-status', 'index', 'issues')?>" issueId="<?=$this->issue->id?>"><?=$this->translate('Статус/срок')?></a>
        <? } ?>
    </td>
</tr>
</table -->

  <div class="issue_view">
    <div class="issue_row">
        <div class="issue_row_label"><?=$this->translate('Добавил')?>:</div>
        <div class="issue_row_content">
            <strong class="txt_green"><a href="<?=$this->url(array('login'=>$this->issue->adder_login), 'user_profile')?>"><?=$this->issue->adder_name?></a></strong>
        </div>
    </div>
    <div class="issue_row">
        <div class="issue_row_label"><?=$this->translate('Исполнители')?>:</div>
        <div class="issue_row_content">
            <strong class="txt_green">
                <? $i = 0 ?>
                <? foreach ($this->issue->users as $userId=>$userName) { ?>
                    <? if ($i > 0) { ?> , <? } ?>
                    <a href="<?=$this->url(array('login'=>$userId), 'user_profile')?>"><?=$userName?></a>
                    <? ++$i ?>
                <? } ?>
            </strong>
        </div>
    </div>
    <div class="issue_row">
        <div class="issue_row_label"><?=$this->translate('Дата создания')?>:</div>
        <div class="issue_row_content">
            <strong class="txt_green"><?=$this->formatDate($this->issue->date_added, TRUE)?></strong>
        </div>
    </div>
    <div class="issue_row">
        <div class="issue_row_label"><?=$this->translate('Последнее обновление')?>:</div>
        <div class="issue_row_content">
            <strong class="txt_green"><?=$this->formatDate($this->issue->date_changed, TRUE)?> / <a href="<?=$this->url(array('login'=>$this->issue->changer_login), 'user_profile')?>"><?=$this->issue->changer_name?></a></strong>
        </div>
    </div>
    <div class="issue_row">
        <div class="issue_row_label"><?=$this->translate('Конечный срок исполнения')?>:</div>
        <div class="issue_row_content">
            <div class="sublabel">
                <span class="txt_red <?=$this->issue_ChangeStatusDialog()->getDateDueClass()?>" dateDue="<?=$this->issue->date_due?>" issueId="<?=$this->issue->id?>"><?=$this->formatDate($this->issue->date_due)?></span>
            </div>
            <? if (count($this->issue->date_due_history)) { ?>
                <div class="subcontent">
                    <a href="#" class="div_toggler" dest="date_due_history"><?=$this->translate('История изменений')?></a>
                    &nbsp;&nbsp;
                    <a href="#" class="div_toggler" dest="date_due_history">
                        <img src="<?=$this->skin()->url()?>images/issues/arr_down.gif" class="issue_arrow"/>
                        <img src="<?=$this->skin()->url()?>images/issues/arr_up.gif" class="issue_arrow hidden"/>
                    </a>
                </div>
                <div class="subcontent date_due_history toggled">
                    <?=$this->issue_DateDueHistoryBox($this->issue->date_due_history)?>
                </div>
            <? } ?>
        </div>
    </div>
    <div class="issue_row">
        <div class="issue_row_label"><?=$this->translate('Состояние')?>:</div>
        <div class="issue_row_content">
            <div class="sublabel">
                <strong class="txt_green"><span class="<?=$this->issue_ChangeStatusDialog()->getStatusClass()?>" status="<?=$this->issue->status?>" issueId="<?=$this->issue->id?>"><?=$this->issue_Status($this->issue)?></span></strong>
            </div>
            <? if (count($this->issue->status_history)) { ?>
                <div class="subcontent">
                    <a href="#" class="div_toggler" dest="status_history"><?=$this->translate('История изменений')?></a>
                    &nbsp;&nbsp;
                    <a href="#" class="div_toggler" dest="status_history">
                        <img src="<?=$this->skin()->url()?>images/issues/arr_down.gif" class="issue_arrow"/>
                        <img src="<?=$this->skin()->url()?>images/issues/arr_up.gif" class="issue_arrow hidden"/>
                    </a>
                </div>
                <div class="subcontent status_history toggled">
                    <?=$this->issue_StatusHistoryBox($this->issue->status_history)?>
                </div>
            <? } ?>
        </div>
    </div>
    <div class="issue_row">
        <div class="issue_row_label"><?=$this->translate('Тема')?>:</div>
        <div class="issue_row_content">
            <strong class="txt_green"><?=$this->issue->subject?></strong>
        </div>
    </div>
    <div class="issue_row">
        <div class="issue_row_label"><?=$this->translate('Описание')?>:</div>
        <div class="issue_row_content">
            <?=$this->issue->text?>
        </div>
    </div>
  </div>


<? $this->headStyle('
    div.toggled {
        display: none;
    }
    .issue_arrow.hidden {
        display: none;
    }
')?>

<? $this->headScript('SCRIPT', '
    $(function(){
        /* show,hide date_due_history and status_history tables */
        $("a.div_toggler").click(function(e){
            e.preventDefault();
            var $this = $(this);
            var dest = $this.attr("dest");
            var selector = "div."+dest;
            var vis = $(selector+":visible");
            var hid = $(selector+":hidden");
            vis.hide();
            hid.show();
            
            selector = ".div_toggler[dest="+dest+"] .issue_arrow";
            vis = $(selector+":visible");
            hid = $(selector+":hidden");
            vis.hide();
            hid.show();
        });
    });
')?>

<?=$this->issue_ChangeStatusDialog(TRUE)?>

<? $this->headScript('SCRIPT', '
    $(function(){

        $("body").bind("dialog_'.$this->issue_ChangeStatusDialog()->getDialogId().'__afterSubmit", function(e){
            $.getJSON("'.$this->stdUrl(array('id'=>$this->issue->id), 'ajax-get-history', 'index', 'issues').'", function(history){
                $("div.date_due_history").html(history.dateDue);
                $("div.status_history").html(history.status);
            });
        });
    });
')?>
