<div class="breadcrumbs">
    <div class="center">
        <a href="<?= $this->url(array(), 'lab-index') ?>">Главная<span></span></a>
    </div>
    <div class="center">
        <a href="<?= $this->url(array(), 'lab-arduino-lab1') ?>">Лабораторная работа 1<span></span></a>
    </div>
    <div class="center">
        <a href="javascript:void(0)">Запуск скетча<span></span></a>
    </div>
</div>
<div class="content home center">
    <h2 style="text-align: center;">Запуск скетча</h2>

    <div>
        <h3 style="width: 305px;float: left;">Скетч:</h3>

        <h3 style="width: 630px;">Ответ компилятора:</h3>
        <textarea disabled="disabled"
                  style="margin: 10px;width: 270px;height: 275px;"><?= $this->data->sketch ?></textarea>

        <textarea disabled="disabled" style="margin: 10px; width: 630px; height: 275px;">
            <?= mb_convert_encoding($this->console, "utf-8", "windows-1251"); ?>
        </textarea>
    </div>
    <div style="margin-top: 20px">
        <h3>I/O:</h3>

        <form>
            <input type="text" id="command"/>
            <input type="submit" id="command_submit" value="Послать">
            <div class="cleaner"></div>
            <textarea style="margin: 0px; width: 385px; height: 110px;" id="command_out"></textarea>
        </form>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#command_submit').click(function(e){
            e.preventDefault();
            $('.alert').remove();
            var command = $('#command').val();
            $('#command_submit').val('Loading...');

            if (command != '') {
                $.ajax({
                    url: "<?= $this->stdUrl(array('reset' => true), 'ajax-send-to-serial', 'labs_arduino', 'lab') ?>",
                    type: "POST",
                    data: {write: command},
                    dataType: "json",
                    success: function (msg) {
                        $('#command_submit').val('Послать');
                        if (msg.success) {
                            $('#command_out').val($('#command_out').val() + msg.str);
                        } else {
                            $('#command').before('<p class="alert" style="color: red;">'+msg.error+'</p>');
                        }
                    }
                });
            } else {
                $('#command').before('<p class="alert" style="color: red;">Поле не может быть пустым</p>');
            }
        })
    })
</script>