<div class="breadcrumbs">
    <div class="center">
        <a href="<?= $this->url(array(), 'lab-index') ?>">Главная<span></span></a>
    </div>
    <div class="center">
        <a href="<?= $this->url(array(), 'lab-arduino-lab1') ?>">Лабораторная работа 1<span></span></a>
    </div>
    <div class="center">
        <a href="javascript:void(0)">Запуск скетча<span></span></a>
    </div>
</div>
<div class="content home center">
    <h2 style="text-align: center;">Запуск скетча</h2>
    <input type="hidden" id="sketch_id" data-id="<?= $this->data->id ?>">
    <p style="text-align: center; width: 400px; margin: 0 auto">
        До конца выполнения лабораторной работы осталось*:
    </p>
    <h1 id="timeout" style="text-align: center; margin: 10px"></h1>
    <p style="text-align: center; width: 400px; margin: 0 auto">
        (*) Перезагрузив страницу вы не сможете восстановить работу
    </p>
    <div>
        <h3 style="width: 305px;float: left;">Скетч:</h3>

        <h3 style="width: 630px;">Ответ компилятора:</h3>
        <textarea id="sketch"
                  style="margin: 10px;width: 270px;height: 275px;"><?= $this->data->sketch ?></textarea>

        <textarea disabled="disabled" id="command_line" style="margin: 10px; width: 630px; height: 275px;">
            <?= mb_convert_encoding($this->console, "utf-8", "windows-1251"); ?>
        </textarea>
    </div>
    <div class="cleaner"></div>
    <div style="text-align: center">
        <form>
            <input type="submit" id="reload" value="Перезаписать" style="margin: 10px 0;">
        </form>
    </div>
    <div class="cleaner"></div>
    <div id="div_video" style="text-align: center;width: 57%;float: left;margin-right: 20px;">
        <video id="video" src="http://localhost:8080/desktop.ogg" autoplay="autoplay" style="width: 525px" />
    </div>
    <div style="width: 40%;overflow: hidden;margin-bottom: 20px;">
        <h3>Input/Output:</h3>

        <form>
            <input type="text" id="command"/>
            <input type="submit" id="command_submit" value="Послать" style="margin-top: 10px;">
            <div class="cleaner"></div>
            <textarea style="margin: 0px; width: 378px; height: 130px;" id="command_out"></textarea>
        </form>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#command_submit').click(function(e){
            e.preventDefault();
            $('.alert').remove();
            var command = $('#command').val();

            if (command != '') {
                $('#command_submit').attr('disabled', 'disabled').val('Loading...');
                $.ajax({
                    url: "<?= $this->stdUrl(array('reset' => true), 'ajax-send-to-serial', 'labs_arduino', 'lab') ?>",
                    type: "POST",
                    data: {write: command, id: $('#sketch_id').data('id')},
                    dataType: "json",
                    success: function (msg) {
                        $('#command_submit').attr('disabled', false).val('Послать');
                        if (msg.success) {
                            $('#command').val('');
                            $('#command_out').val($('#command_out').val() + msg.str);
                        } else {
                            $('#command').before('<p class="alert" style="color: red;">'+msg.error+'</p>');
                        }
                    }
                });
            } else {
                $('#command').before('<p class="alert" style="color: red;">Поле не может быть пустым</p>');
            }
        });
        $('#reload').click(function(e){
            e.preventDefault();
            $('.alert').remove();
            var sketch = $('#sketch').val();

            if (sketch != '') {
                $('#reload').attr('disabled', 'disabled').val('Loading...');
                $.ajax({
                    url: "<?= $this->stdUrl(array('reset' => true), 'ajax-reload', 'labs_arduino', 'lab') ?>",
                    type: "POST",
                    data: {sketch: sketch},
                    dataType: "json",
                    success: function (msg) {
                        $('#reload').attr('disabled', false).val('Перезаписать');
                        if (msg.success) {
                            $('#sketch').val(msg.sketch);
                            $('#command_line').val(msg.console);
                            $('#sketch_id').data('id', msg.id);
                        } else {
                            $('#sketch').before('<p class="alert" style="color: red;">'+msg.error+'</p>');
                        }
                    }
                });
            } else {
                $('#sketch').before('<p class="alert" style="color: red;">Поле не может быть пустым</p>');
            }
        })

        var myCounter = new Countdown({
            seconds: <?= 60 * Model_Object_ArduinoLine::MINUTES_FOR_USER ?>,  // number of seconds to count down
            onUpdateStatus: function(sec){
                var hours = parseInt(sec / 3600 ) % 24;
                var minutes = parseInt( sec / 60 ) % 60;
                var seconds = sec % 60;

                var result = (hours < 10 ? "0" + hours : hours) + ":" + (minutes < 10 ? "0" + minutes : minutes) + ":" + (seconds  < 10 ? "0" + seconds : seconds);
                $('#timeout').html(result);
            }, // callback for each second
            onCounterEnd: function(){
                $('#div_video').remove();
                $('#command_submit').remove();
                $('#reload').remove();
                $('#command').remove();

                myCounter.stop();
                $.ajax({
                    url: "<?= $this->stdUrl(array('reset' => true), 'ajax-close-serial', 'labs_arduino', 'lab') ?>",
                    type: "POST",
                    data: {id: $('#sketch_id').data('id')},
                    dataType: "json",
                    success: function () {
                        return '';
                    }
                });
            } // final action
        });
        myCounter.start();
    });
    window.onbeforeunload = function (e) {
        $.ajax({
            url: "<?= $this->stdUrl(array('reset' => true), 'ajax-close-serial', 'labs_arduino', 'lab') ?>",
            type: "POST",
            data: {id: $('#sketch_id').data('id')},
            dataType: "json",
            success: function () {
                return '';
            }
        });
    }
</script>