<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'lab-index')?>">Главная<span></span></a>
    </div>
</div>
<div class="content home center">
    <div class="mcol">
        <? if ($this->submitted AND $this->success) { ?>
            <div class="title_h3">
                <h3>Восстановление пароля</h3>
            </div>
            <div class="mcol_h2">
                <h2>Спасибо, Ваш новый пароль был отправлен к вам на почтовый ящик.</h2>
            </div>
        <? } else { ?>
            <div class="title_h3">
                <h3>Забыли пароль?</h3>
            </div>
            <div class="mcol_h2">
                <h2>Пожалуйста, введите Email адрес, который Вы указывали при регистрации!</h2>
                <?= $this->renderForm($this->form, 'front_form.phtml') ?>
            </div>
        <? } ?>
    </div>
</div>

    
