<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'lab-index')?>">Главная<span></span></a>
    </div>
</div>
<div class="content home center">
    <div class="mcol">
        <div class="title_h3">
            <h3>Зарегистрируйтесь или войдите</h3>
        </div>

        <div class="reg">
            <h2>Зарегистрируйстесь</h2>
            <a class="button" href="<?= $this->stdUrl(array(''), 'lab-user-register') ?>">
                <span>Регистрация</span>
            </a>
        </div>
        <div class="login">
            <h2>Введите свои данные для входа</h2>
            <? if ($this->ER == TRUE) { ?>
                <div class="login_error" style="color: red;">
                    <p>Указанный 'Email' и/или 'пароль' неверный.</p>
                </div>
            <? } ?>
        </div>
        <?= $this->renderForm($this->form) ?>
        <a class="button" style="position: absolute;margin-top: -28px;margin-left: 300px;"
           href="<?= $this->stdUrl(array(''), 'forgot-password', 'auth', 'lab') ?>">
            <span>Восстановление пароля</span>
        </a>
    </div>
</div>
