<div class="mcol">
	<div class="title_h3">
		<h3>Зарегистрируйтесь или войдите</h3>
	</div>
	
	<div class="reg">
		<h2>Зарегистрируйстесь</h2>
		<a class="button" href="<?=$this->stdUrl(array(''),'lab-user-register')?>">
			<span>Регистрация</span>
		</a>
	</div>
	<div class="login">
		<h2>Введите свои данные для входа</h2>
		<?if ($this->ER == TRUE){?>
			<div class="login_error">
				<p>Указанный 'Email' и/или 'пароль' неверный.</p>
			</div>
		<?}?>
	</div>
	<?=$this->renderForm($this->form)?>
</div>
