<div class="breadcrumbs home"></div>
<div class="banners" style='background: url("<?=App_Resource::getUploadsUrl($this->main_banner->image_id_filename)?>") no-repeat scroll center 0 transparent;'>
    <div class="main_text">
    </div>
</div>
<div class="cleaner"></div>
<div class="content home center">
    <div class="hidden"><h1>title</h1></div>
    <div class="bonus-program">
    <h2><span style="font-size: 24px;">some about</span><br />
    </h2>
    <p></p>
    </div>
    <div class="cleaner"></div>
</div>
