<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'shop-index')?>">Главная<span></span></a>
        <span class="current">Результаты поиска</span>
    </div>
</div>

<div class="content page">
    <div class="center search">
        <?if ( $this->total_count ){?>
            <h2>Результаты поиска «<span class="search_params"><?= $this->search_params?></span>»</h2>
            <p>Найдено <?= $this->items_count?> изделий и <?= count($this->pages)?> страниц</p>
            
            <?if ( $this->pages_count){?>
                <div class="section">Страницы<span></span></div>
                <div class="cleaner"></div>
                <div class="search_result">
                <? foreach($this->pages as $page) {?>
                    <div class="info">
                        <h2 class="page_title"><a href="<?=$this->url(array('seo_id' => $page->seo_id), 'shop-page')?>"><?= $page->title?></a></h2></br>
                        <?= $this->quotes[$page->id]?>
                    </div>
                <?}?>
                </div>
            <?}?>
            <?if ( $this->items_count ){?>
                <div class="section">Товары<span></span></div>
                <div class="cleaner"></div>
                <script type="text/javascript">
                    $(document).ready(function(){
                        $('.show_info').live('mouseenter', function(){
                            $(this).parent().find('.info').show();
                        })
                        $('.item .info').live('mouseleave', function(){
                            $('.item .info').hide();
                        })
                    });
                </script>
                <? $counter = 0; ?>
                <div class="items">
                    <?foreach($this->items as $key => $item){?>
                        <? $counter++; ?>
                        <?= ( $counter == 1  ) ? '<div class="block left">' : ''?>
                        <?= ( $counter == 6  ) ? '<div class="cleaner"></div><div class="block line">' : ''?>
                        <?= ( $counter == 11  ) ? '<div class="block right">' : ''?>
                            <div class="item <?= ( in_array($counter, array(2,3,8,12,13)) ) ? 'wide' : ''?><?= in_array($counter, array(5,10)) ? 'large' : ''?>" >
                                <? if (in_array($counter, array(5,10)))
                                        $preview = 'rc_id_preview4';
                                    elseif (in_array($counter, array(2,3,8,12,13)))
                                        $preview = 'rc_id_preview3';
                                    else $preview = 'rc_id_preview2';
                                ?>
                                <a class="show_info" href="javascript:void(0);">
                                    <table class="items_align"><tr><td class="item_align">
                                        <a class="items_align" href="<?=$this->url(array('category' => $item->category_seo_id, 'seo_id' => $item->seo_id), ( $item->category_seo_id == 'exclusive' ) ? 'shop-exclusive' : 'shop-item')?>">
                                            <?if (isset($this->galleries[$item->id][0])){?>
                                                <span><img  src="<?=App_Resource::getUploadsUrl($this->galleries[$item->id][0][$preview])?>" alt="" /><span>
                                            <?}?>
                                        </a>
                                    </td></tr></table>
                                </a>
                                <!--a class="show_info" href="javascript:void(0);"></a-->
                                <a href="<?=$this->url(array('category' => $item->category_seo_id,'seo_id' => $item->seo_id), ( $item->category_seo_id == 'exclusive' ) ? 'shop-exclusive' : 'shop-item')?>">
                                <div class="info">
                                    <div class="short">
                                        <?= $item->brief?>
                                        <!--?if( $item->price != 0 ){?>
                                            <div class="price">ЦЕНА<span><?=$item->price?> грн.</span></div-->
                                        <!--?}?-->
                                        <div>ПОДРОБНЕЕ</div>
                                    </div>
                                </div>
                                </a>
                            </div>
                        <?= ( in_array($counter, array(4,9,14)) || $key+1 == count($this->items) && !in_array($counter, array(5, 10))) ? '</div>' : ''?>
                        <?if ($counter == 14){ $counter = 0; }?>
                    <?}?>
                </div>
                <div class="cleaner"></div>
            <?}?>            
        <?} else {?>
            <? if( mb_strlen($this->search_params, 'UTF-8') < 3 ){?>
                <h2>Запрос должен содержать не менее 3 символов.</h2>
            <?} else {?>
                <h2>По запросу «<span class="search_params"><?= $this->search_params?></span>» ничего не найдено.</h2>
            <?}?>
        <?}?>
           
    </div>
    <div class="cleaner"></div>
    <span class="items_preloader"></span>    
</div>
<script type="text/javascript">
    $(document).ready(function(){
        <?if ($this->items_count > 56){?>
            $(window).scrollTop(0);
            var page = 2;        
            var upload = true;
            $(window).scroll(function(){           
                var bottom = $(document).height() - $(window).height() - $(window).scrollTop();
                if (bottom < 1300 && upload == true) {
                    $('.items_preloader').toggle();
                    upload = false;
                    var last_position = $('.items .item').length;
                    $.ajax({
                        url: "<?= $this->url(array(), 'shop-ajax-get-next-items') ?>",
                        type: "POST",
                        data: { 
                                page: page,
                                param: '<?= $this->search_params?>',
                                page_type: 'search'
                            },
                        dataType: "json",
                        success: function(data){
                            $('.items').append(data.items);
                            $('.items_preloader').toggle();
                            page++;
                            if ( $('.items .item').length < <?= $this->items_count?>)
                                upload = true;
                        }
                    })
                }
            });
        <?}?>
    });
</script>
<script type="text/javascript">
    $(function(){
        (function($){
        $.fn.liHighLight = function(params){
            var p = $.extend({
                words: '',
                class: 'highlight'
            }, params);
            return this.each(function(){
                var wrap = $(this);
                var wArr = $.trim(p.words).split(' ');
                htmlreplace($(this));
                function htmlreplace(element){
                    if (!element) element = document.body;
                    var wrap = $(element).contents().each(function () {
                        if (this.nodeType === 3) {
                            var result = $(this).text();
                            for(i = 0; i < wArr.length; i++){
                                result = result.replace(new RegExp(wArr[i],'gi'),'<strong class="'+p.class+'">$&</strong>');
                            }
                            $(this).after(result).remove();
                        } else {
                            htmlreplace(this);
                        };
                    });
                };
            });
        };
        })(jQuery);
            $('.center.search .search_result').liHighLight({
                words:'<?= $this->search_params?>',
                class: 'highlight'
            });
        });
</script>
