<? $this->headScript(Zend_View_Helper_HeadScript::FILE, $this->stdUrl(array('reset'=>TRUE)).'js/admin/unicorn.dashboard.js') ?>

<? $this->pageTitle($this->translate('Новости и рассылки')); ?>
<div class="row-fluid">
<div class="span12 center" style="text-align: center;">			
    <ul class="stat-boxes">
        <li class="popover-orders" style="cursor: pointer;">
            
            <div class="right">
                <strong><?= $this->totalSubscribers?></strong>
                <?=$this->translate('Подписчиков')?>
            </div>
        </li>
    </ul>
</div>
</div>
 <script>
$(document).ready(function(){
    
    $('.popover-orders').popover({
        placement: 'bottom',
        trigger: 'hover',
        html : true,
         
        content: function() {
           var id = $(this).attr('id');
          return $('#for-'+id).html();
        }
    });
    $('.popover-orders').click(function(){
        location.href = '<?=$this->stdUrl(array(), 'subscribers-list')?>';
    });
})
</script>
<?=$this->adminMassForm('formStart')?>
<div class="widget-box collapsible">
    <div class="widget-title">
        <a href="#collapseThree" data-toggle="collapse">
			<span class="icon"><i class="icon-pencil"></i></span>
                <h5><?=$this->translate('Действия с новостями')?></h5>
        </a>
    </div>
    <div class="collapse" id="collapseThree">
        <div class="widget-content">
                <?=$this->adminMassForm('actions')?>
        </div>
    </div>
</div>

<div class="widget-box table">
    <div class="widget-title"><h5><?=$this->translate('Список новостей')?></h5>
    <div class="buttons">
        <a href="<?=$this->stdUrl(array('reset'=>TRUE), 'edit', 'admin-news')?>" class="btn btn-mini">
        <i class="icon-file"></i>
        <?=$this->translate('New')?>
        </a>      
    </div>
    </div>
    <div class="widget-content nopadding">  
<? $i = 0 ?>

    <table cellspacing="0" class="table table-bordered table-striped table-hover table-no-external-border">
      <tr>
        <th width="50px"><?=$this->adminMassForm('checkAll')?></th>
        <th><?=$this->translate('Date')?></th>
        <th><?=$this->translate('Image')?></th>
        <th><?=$this->translate('News title')?></th>
        <th><?=$this->translate('Seo id')?></th>
        <th><?=$this->translate('Topic')?></th>
        <th class="actions2" width="25%"><?=$this->translate('Actions')?></th>
      </tr>

<? foreach ($this->news as $row) { ?>
      <tr >
        <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
        <td> <?=$this->formatDate($row['date_publish'])?></td>
        <td> <?=$this->html_Img($row['rc_id_preview'])?><br /></td>
        <td> <?=$row['title']?> </td>
        <td><?=$row['seo_id']?></td>
        <td><?=$row['ntopic_name']?> <?=$row['ntopic_news_count']?'('.$row['ntopic_news_count'].')':''?></td>
        <td class="actions2">
            <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit')?>"><?=$this->translate('Edit')?></a>
             /
            <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete')?>"><?=$this->translate('Delete')?></a>
             /
            <a class="txt_blue" href="<?=$this->stdUrl(array('id'=>$row['id']), 'send-subscribers')?>"><?=$this->translate('Send to subscribers')?></a>
        </td>
      </tr>

    <? ++$i ?>
<? } ?>


    </table>

</div>
    <?=$this->paginationControl($this->news)?>
    <?=$this->adminMassForm('formEnd')?>
</div>
