
<? $this->pageTitle($this->translate('Список подписчиков')); ?>

<?=$this->adminMassForm('formStart')?>

<div class="widget-box table">
    <div class="widget-title"><h5><?=$this->translate('Список подписчиков')?></h5>

    </div>
    <div class="widget-content nopadding">  
<? $i = 0 ?>

    <table cellspacing="0" class="table table-bordered table-striped table-hover table-no-external-border">
      <tr>
        <th><?=$this->translate('Email')?></th>
      </tr>

<? foreach ($this->subscribers as $row) { ?>
      <tr>
        <td> <?= $row->email?></td>
      </tr>

    <? ++$i ?>
<? } ?>

    </table>

</div>
    <?=$this->paginationControl($this->subscribers)?>
    <?=$this->adminMassForm('formEnd')?>
</div>
