                    <div class="white-box-top" >
                        <div class="white-box-bottom">
                          <div class="white-box-center">
<!--                            <div class="cleaner"></div>-->
                            <div id="center-box">
                                <div class="text-box">
                                    <div class="article_navigate">
                                        <a href="">Главная</a><span>&rarr;</span><a href="">Каталог</a><span>&rarr;</span><a href=""><b>Механические автоматы</b></a>
                                    </div>
                                </div>
                                <div class="text-box-border"><img alt="" src="images/spacer.gif" width="1000" height="2" border="0" /></div>
                            </div>
                            <div id="article">
                                <h2>Статьи</h2>
                                <div class="article_content">
                                    <div class="article_content_inner">
                                    
                                        <div class="article_text">
                                            <div class="article_text_more">
                                              <? if ($this->topic) { ?>
                                                <div class="article_header">
                                                    <span><?=$this->topic->name?></span>
                                                </div>
                                                <p>
                                                    <?=$this->topic->brief?>
                                                </p>
                                              <? } ?>
                                            </div>
                                        </div>
                                        
                                        <? if ($this->topics AND $this->topics->count()) { ?>
                                        <div class="article_text">
                                            <div class="article_text_bottom">
                                                <div class="art_bottom_lnks">
                                                    <span>Темы</span>
                                                    <? foreach ($this->topics as $row) { ?>
                                                        <p><a href="<?=$this->url(array('seo_id'=>$row->seo_id), 'infosite-article-index')?>"><?=$row->name?></a></p>
                                                    <? } ?>
                                                </div>
                                            </div>
                                        </div>
                                        <? } ?>

                                        <? if ($this->articles AND $this->articles->count()) { ?>
                                        <div class="article_text">
                                            <div class="article_text_bottom">
                                                <div class="art_bottom_lnks">
                                                    <span>Статьи</span>
                                                    <? foreach ($this->articles as $row) { ?>
                                                        <p><a href="<?=$this->url(array('seo_id'=>$row->seo_id, 'topic_seo_id'=>$this->topic?$this->topic->id:''), 'infosite-article-detailed')?>"><?=$row->title?></a></p>
                                                    <? } ?>
                                                </div>
                                            </div>
                                        </div>
                                        <? } ?>

                                        <div class="article_content_bottom"></div>
                                    </div>                                    
                                </div>

                            </div>
                            <div class="cleaner"></div>
                            </div>
                        </div>
                    </div>
