<div class="text_page">
  <h2><?=$this->translate('Frequently Asked Questions')?></h2>
  <div class="content_wrapp">
    <? foreach ($this->faqs as $faq) { ?>
    <p>
        <a href="<?=$this->url(array('seo_id'=>$faq['seo_id']), 'faq_detailed')?>"><strong><?=$faq['quest']?></strong></a>
        <?=$faq['brief']?>
    </p>
    <? } ?>
  </div>
  <?=$this->paginationControl($this->faqs)?>
</div>

