<div class="mcol">
	<div class="title_h3">
		<h3>Пароль</h3>
	</div>
    <?if($this->erorUpPasswordNew == TRUE){?>
	<div class="message">
	    <h2>Поля Подтвердите пароль и Новый пароль должны совпадать.</h2>
	</div>
    <?}?>
    <?if($this->erorUpPasswordOld == TRUE){?>
	<div class="message">
		<h2>Неверный старый пароль.</h2>
	</div>
    <?}?>
	<span class="inputRequirementTitle">поля, отмеченные *, обязательны для заполнения</span>
	
	<?=$this->renderForm($this->form)?>
	
	<a href="<?=$this->url(array(), 'lab-my_cabinet')?>"><img src="<?=$this->skin()->url()?>/images/button_back.jpg" alt="Назад" title=" Назад " class="button_pass" /></a>
	
		
</div>