<div class="mcol">
	<div class="title_h3">
		<h3>Ваши персональные данные</h3>
	</div>
	<?if($this->sucsessUpdete == TRUE){?>
	<div class="message">
		<h2>Ваши данные обновлены!</h2>
	</div>
	<?}?>
	<?if($this->sucsessUpdetePass == TRUE){?>
	<div class="message">
		<h2>Ваш пароль изменён!</h2>
	</div>
	<?}?>					
							
	<div class="cabinet_left">
		<h2>Добро пожаловать!</h2>
		<p>Это Ваша персональная страница, где Вы можете просмотреть выполненные заказы, а также список просмотренных Вами товаров</p>
		<p>Сейчас Вы можете полностью управлять своими персональными данными.</p>	
	</div>
	
	<div class="cabinet_right">
		<h2>Персональная информация</h2>	
		<p><a href="<?=$this->url(array(), 'lab-my_cabinet-persons')?>">Посмотреть или изменить Ваши персональные данные</a></p>
		<p><a href="<?=$this->url(array(), 'lab-my_cabinet-changepassword')?>">Изменить пароль</a></p>
		
<!--		<h2>Мои заказы</h2>	-->
<!--		--><?//foreach ($this->orders as $orders){?>
<!--			<div class="my_order">-->
<!--				<ul>-->
<!--					<li>--><?//=$orders['date_added']?><!--</li>-->
<!--					<li>Номер заказа: --><?//=$orders['id']?><!--</li>-->
<!--					<li>Сумма:--><?//=$orders['total']?><!-- Р</b></li>-->
<!--				</ul>-->
<!--				<p>Статус заказа: <strong>-->
<!--									--><?//if ($orders['status'] == 0) {
//										echo 'Отменен';
//										}
//										else if($orders['status'] == 1){
//										echo 'Выписан';
//										}
//										else if($orders['status'] == 2){
//										echo 'В обработке';
//										}
//										else if($orders['status'] == 3){
//										echo 'В доставке';
//										}
//										else if($orders['status'] == 4){
//										echo 'Выполнен';
//										}
//										else if($orders['status'] == 5){
//										echo 'Оплачен';
//										}
//										else if($orders['status'] == 6){
//										echo 'Не оплачен';
//										}
//										?>
<!--									</strong></p>-->
<!--				<img src="--><?//=$this->skin()->url()?><!--images/small_view.jpg" alt="Смотреть" title=" Смотреть " width="74" height="21" class="buttons" style="border: none;" onclick="window.open('--><?//=$this->url(array('id' => $orders['id']), 'lab-order-print')?>//', 'popup', 'toolbar=0, width=840, height=600')"/>
//			</div>
//		<?//}?>
	</div>
</div>