<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'shop-index')?>">Главная<span></span></a>
        <span class="current"><?=$this->page->title?></span>
    </div>
</div>

<?if ( $this->page->rc_id_filename || $this->page->banner){?>

    <?if ( $this->page->rc_id_filename && !$this->page->banner){?>
        <table class="page_img"><tr><td>
            <img src="<?= App_Resource::getUploadsUrl($this->page->rc_id_filename)?>" alt="" />
            <?if ( $this->page->video ){?>
                <span class="page_play"></span>
            <?}?>
        </td></tr></table>

    <?} elseif ( $this->page->banner && !$this->page->rc_id_filename) {?>
        <div class="page_banner">
            <?= $this->page->banner?>
            <?if ( $this->page->video ){?>
                <span class="page_play">
                    <span>(смотреть видео)</span>
                </span>
            <?}?>
        </div>

    <?}?>

    <?if ( $this->page->video ){?>
        <div class="page popup video">
            <span class="close"></span>
            <?= $this->page->video?>
        </div>    
    <?}?>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.page_play').click(function(){
                $('.popup.video').show();
            })                    
            $('.popup .close').click(function(){
                $(this).parent().hide();
            })
        });
    </script>

<?}?>

<div class="content page <?= $this->page->driver?>">
    <div id="map_canvas" class="map <?= $this->page->driver?>"></div>
    <div class="center">  
        <?=$this->page['full']?>
        <?=$this->driverHtml?>
    </div>
    <div class="cleaner"></div>
</div>
