<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'lab-index')?>">Главная<span></span></a>
    </div>
</div>
<div class="content home center">
    <div class="mcol">
        <div class="title_h3">
            <h3>Пароль</h3>
        </div>
        <? if ($this->erorUpPasswordNew == TRUE) { ?>
            <div class="message">
                <h2>Поля Подтвердите пароль и Новый пароль должны совпадать.</h2>
            </div>
        <? } ?>
        <? if ($this->erorUpPasswordOld == TRUE) { ?>
            <div class="message">
                <h2>Неверный старый пароль.</h2>
            </div>
        <? } ?>
        <span class="inputRequirementTitle">все поля обязательны для заполнения</span>

        <?= $this->renderForm($this->form) ?>
    </div>
</div>