<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'lab-index')?>">Главная<span></span></a>
    </div>
</div>
<div class="content home center">
    <div class="mcol">
        <div class="title_h3">
            <h3>Редактирование персональных данных</h3>
        </div>
        <span class="inputRequirementTitle">все поля обязательны для заполнения</span>
        <?= $this->renderForm($this->form) ?>
    </div>
</div>