<?=$this->doctype(Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL)?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?=$this->headMeta()?>
		<?=$this->headTitle()?>
		<?=$this->headLink()?>
		<link type="text/css" rel="stylesheet" href="<?=$this->skin()->url()?>css/style.css" />
		<script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery.min.js"></script>
	</head>
	
    <body>
		<div id="header_not_index">
			<div id="header">
				<?=$this->box_Top()?>
				<?=$this->menu('top')?>
			</div>	
		</div>
	
		<div id="page">
			<?=$this->layout()->content?>
		</div>	
		
		<?=$this->box_Footer()?>
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-27164144-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script> 
    </body>
</html>