<?=$this->doctype(Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL)?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?=$this->headMeta()?>
		<?=$this->headTitle()?>
		<?=$this->headLink()?>
        <link type="text/css" rel="stylesheet" href="<?=$this->skin()->url()?>css/style.css" />
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery-1.6.4.min.js"></script>
    </head>
	
    <body>
        <div class="header">
            <?=$this->box_Header()?>
        </div>
        <?=$this->layout()->content?>
        <?=$this->box_Footer()?>
    </body>
</html>