<?=$this->doctype(Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL)?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?=$this->headMeta()?>
		<?=$this->headTitle()?>
		<?=$this->headLink()?>
        <meta name="description" content="Ювелирный дом SA&amp;GA. Продукция «SA&amp;GA» выходит под фирменным торговым знаком, зарегистрированным в Государственном Департаменте интеллектуальной собственности. Все ювелирные украшения сертифицированы Восточной геммологической лабораторией экспертизы и сертификации. Каталог ювелирных изделий из золота, эксклюзивные изделия – золотые серьги, золотые кольца, золотые браслеты, обручальные кольца, изделия с бриллиантами, украшения с жемчугом." />
        <meta name="Keywords" content="ювелирный магазин каталог, ювелирные магазины киева, сайты ювелирных магазинов, ювелирный магазин официальный сайт, золотые изделия каталог, купить золотое кольцо, кольцо купить киев, купить обручальные кольца, обручальные кольца киев, купить кольцо с бриллиантом, купить кольцо с жемчугом, купить серьги золотые, серьги кольца купить, купить серьги с бриллиантом, купить серьги с жемчугом, купить золотой браслет, жемчужное ожерелье, золотой мужской перстень, ювелирный интернет-магазин" />
		<meta name="google-site-verification" content="aFR2HASuZ9McQ87Iv7JlfQKtoPF3Duqtfw5p2M9WZ_8" />
        <link type="text/css" rel="stylesheet" href="<?=$this->skin()->url()?>css/style.css" />
        <link type="text/css" rel="stylesheet" href="<?=$this->skin()->url()?>css/video-js.css" />
        <link type="text/css" rel="stylesheet" href="<?=$this->skin()->url()?>css/nivo-slider.css" media="screen" />
        <link rel="shortcut icon" href="<?=$this->skin()->url()?>img/Saga.ico" type="image/x-icon" />
        <link rel="icon" href="<?=$this->skin()->url()?>img/Saga.ico" type="image/x-icon" />
        <!--link href="http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic" rel="stylesheet" type="text/css" /-->
        <!--link href='http://fonts.googleapis.com/css?family=Roboto:400italic,700italic,700,400&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css' /-->
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery-1.6.4.min.js"></script>
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery.jcarousel.min.js"></script>
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery.nivo.slider.js"></script>
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/video.js"></script>
        <script type="text/javascript">videojs.options.flash.swf = "video-js.swf";</script>
        <style type="text/css">
            #rh-chat {
                left: inherit !important;
                right: 0 !important;
                top: 50% !important;
            }
        </style>
        <script type="text/javascript">
            $(document).ready(function(){
            $('.frozen').mouseenter(function(){
                        $(this).stop().fadeTo(2000, 0);
            });
            $('.xmass-history').mouseleave(function(){
                        $(this).find('.frozen').stop().fadeTo(2000, 1);
            });
            });
        </script>
	</head>
	
    <body>
        <div class="header home">
            <?=$this->box_Header()?>
        </div>
        <?=$this->layout()->content?>
        <?=$this->box_Footer()?>
        
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-27164144-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script> 
    </body>
</html>