<?=$this->doctype(Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL)?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?=$this->headMeta()?>
		<?=$this->headTitle()?>
		<?=$this->headLink()?>
        <?if(strlen($this->headdescription)>0){?>
            <meta name="description" content="<?=$this->headdescription?>" />
        <?}?>
        <?if(strlen($this->headkeywords)>0){?>
    		<meta name="keywords" content="<?=$this->headkeywords?>" />
        <?}?>
        <link type="text/css" rel="stylesheet" href="<?=$this->skin()->url()?>css/style.css" />
        <link rel="shortcut icon" href="<?=$this->skin()->url()?>img/Saga.ico" type="image/x-icon" />
        <link rel="icon" href="<?=$this->skin()->url()?>img/Saga.ico" type="image/x-icon" />
        <!--link href='http://fonts.googleapis.com/css?family=Roboto:400italic,700italic,700,400&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css' /-->
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery-1.6.4.min.js"></script>
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery.jcarousel.min.js"></script>
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/selectBox.js"></script>
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery.ui-slider.js"></script>
	</head>
	
    <body>
        <div class="header">
            <?=$this->box_Header()?>
        </div>
        <?=$this->layout()->content?>
        <?=$this->box_Footer()?>
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-27164144-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script> 
    </body>
</html>