<?=$this->doctype(Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL)?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?=$this->headMeta()?>
		<?=$this->headTitle()?>
		<?=$this->headLink()?>
		<link type="text/css" rel="stylesheet" href="<?=$this->skin()->url()?>css/style.css" />
		<script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery-1.9.1.min.js"></script>
	</head>
	
    <body>
		<div id="header_not_index">
			<div id="header">
				<?=$this->box_Top()?>
				<?=$this->menu('top')?>
			</div>	
		</div>
	
		<div id="page">
			<?=$this->layout()->content?>
		</div>	
		
		<?=$this->box_Footer()?>
    </body>
</html>