<?=$this->doctype(Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL)?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?=$this->headMeta()?>
		<?=$this->headTitle()?>
		<?=$this->headLink()?>
        <meta name="Keywords" content="ювелирный магазин каталог, ювелирные магазины киева, сайты ювелирных магазинов, ювелирный магазин официальный сайт, золотые изделия каталог, купить золотое кольцо, кольцо купить киев, купить обручальные кольца, обручальные кольца киев, купить кольцо с бриллиантом, купить кольцо с жемчугом, купить серьги золотые, серьги кольца купить, купить серьги с бриллиантом, купить серьги с жемчугом, купить золотой браслет, жемчужное ожерелье, золотой мужской перстень, ювелирный интернет-магазин" />
		<link type="text/css" rel="stylesheet" href="<?=$this->skin()->url()?>css/style.css" />
        <link rel="shortcut icon" href="<?=$this->skin()->url()?>img/Saga.ico" type="image/x-icon" />
        <link rel="icon" href="<?=$this->skin()->url()?>img/Saga.ico" type="image/x-icon" />
        <script type="text/javascript" src="<?=$this->skin()->url()?>js/jquery-1.6.4.min.js"></script>

	</head>
	
    <body>
        <div class="header home">
            <?=$this->box_Header()?>
        </div>
        <?=$this->layout()->content?>
        <?=$this->box_Footer()?>
    </body>
</html>