
<form enctype="multipart/form-data"
    <? foreach ($this->form->getAttribs() as $name=>$value) { ?>
        <?=$name?>="<?=$value?>"
    <? } ?>
    class="front_form" 
>
	<? $errors = array_merge($this->form->getErrors(), $this->form->getErrorMessages()) ?>
	

    <? $buttons = array() ?>
    <? $hiddens = array() ?>
    <? $inputs = array() ?>
    
    <? foreach ($this->form->getElements() as $el) {?>
        <? if (($el instanceof Zend_Form_Element_Submit) OR ($el instanceof Zend_Form_Element_Button)) { ?>
            <? $buttons[]=$el ?>
        <? } else if ($el instanceof Zend_Form_Element_Hidden) { ?>
            <? $hiddens[]=$el ?>
        <? } else { ?>
            <? $inputs[]=$el ?>
        <? } ?>
    <? } ?>
    	    		
	<table>

    <? foreach ($inputs as $el) {?>
    	<tr>
    		<td width="150px">
                <? $label = $el->getLabel() ?>
           		<? if ( ! empty($label)) { ?>
           			    <?=$label?>
           			    <? if ($el->isRequired()) {?> <?=$this->formMarkerRequired()?><? } ?> :
        	    <? } ?>
    	    </td>
    		<td width="300px">
                <? if ($errors[$el->getName()]) { ?>
                    <div class="red" style="color:red">
                    <?=$this->form->getElementErrorsFormatted($el->getName(), $errors[$el->getName()])?>
                    </div>
                <? } ?>
                <? if (in_array($el->getType(), array('Zend_Form_Element_Text', 'Zend_Form_Element_Password'))) { ?>
                        <? $el->setAttrib('class', 'input') ?>
                <? } else if ($el->getType() == 'Zend_Form_Element_Select') { ?>
                        <? $el->setAttrib('class', 'select') ?>
                <? } else if ($el->getType() == 'Zend_Form_Element_Textarea') { ?>
                        <? $el->setAttrib('class', 'textarea') ?>
                <? } ?>
                <? $el->setDecorators(array('ViewHelper')) ?>
                <?=$el->render()?>
            </td>
        </tr>
    <? } ?>
	
    	<tr>
    		<td></td>
    		<td>
                <? foreach ($buttons as $btn) { ?>
                    <?=$btn->render()?>
                <? } ?>
                <? foreach ($hiddens as $el) { ?><?=$el->render()?><? } ?>
                <?/*?>    		
    			<a class="button" href="<?=$this->url(array('seo_id'=>$this->page->seo_id), 'shop-page')?>"><?=$this->translate('ОТПРАВИТЬ')?></a>
    			<?*/?>
    		</td>
    	</tr>
    	
    </table>
</form>
