

<? $errors = array_merge($this->form->getErrors(), $this->form->getErrorMessages()) ?>

<form  enctype="multipart/form-data"
    <? foreach ($this->form->getAttribs() as $name=>$value) { ?>
        <?=$name?>="<?=$value?>"
    <? } ?>
>


<table width="100%" cellpadding="0" cellspacing="0" class="tbl_edit">

<? if ($this->form->getText() !== NULL) { ?>
    <tr>
        <td colspan="2">
            <?=$this->form->getText()?>
        </td>
    </tr>
<? } ?>

<? foreach ($errors as $error_key=>$error_text) { ?>
   <? if (is_numeric($error_key)) { ?>
        <tr>
            <td colspan="2"  class="red">
                <?=$error_text?>
            </td>
        </tr>
   <? } ?>
<? } ?>

<? $buttons = array() ?>
<? $hiddens = array() ?>
<? $inputs = array() ?>

<? foreach ($this->form->getElements() as $el) {?>
    <? if (($el instanceof Zend_Form_Element_Submit) OR ($el instanceof Zend_Form_Element_Button)) { ?>
        <? $buttons[]=$el ?>
    <? } else if ($el instanceof Zend_Form_Element_Hidden) { ?>
        <? $hiddens[]=$el ?>
    <? } else { ?>
        <? $inputs[]=$el ?>
    <? } ?>
<? } ?>


<? foreach ($inputs as $el) {?>
    <tr>
        <? $label = $el->getLabel() ?>
        <td class="label"><? if ( ! empty($label)) { ?><label for="<?=$el->getName()?>"><?=$label?><? if ($el->isRequired()) {?> <?=$this->formMarkerRequired()?><? } ?> :</label><? } ?></td>
        <td class="value">
            <? if ($errors[$el->getName()]) { ?>
                <div class="red" style="color:red">
                <?=$this->form->getElementErrorsFormatted($el->getName(), $errors[$el->getName()])?>
                </div>
            <? } ?>
            <? if (in_array($el->getType(), array('Zend_Form_Element_Text', 'Zend_Form_Element_Password'))) { ?>
                    <? $el->setAttrib('class', 'input') ?>
            <? } else if ($el->getType() == 'Zend_Form_Element_Select') { ?>
                    <? $el->setAttrib('class', 'select') ?>
            <? } else if ($el->getType() == 'Zend_Form_Element_Textarea') { ?>
                    <? $el->setAttrib('class', 'textarea') ?>
            <? } ?>
            <? $el->setDecorators(array('ViewHelper')) ?>
            <?=$el->render()?>
        </td>
    </tr>
<? } ?>

<tr>
    <td colspan="2">&nbsp;</td>
</tr>

<tr>
    <td>&nbsp;</td>
    <td align="center">
        <table><tr>
        <? foreach ($buttons as $btn) { ?>
            <td><?=$btn->render()?></td>
        <? } ?>
        </tr></table>
    </td>
</tr>


</table>

<? foreach ($hiddens as $el) { ?><?=$el->render()?><? } ?>

</form>

