<div class="ofzakaz_info">
	<p>
    	<span>Поставщик:</span>
        <br />
        <?=$this->shipment->seller_requisites['name']?>, ИНН <?=$this->shipment->seller_requisites['inn']?>, КПП <?=$this->shipment->seller_requisites['kpp']?>,
        <br />
        <?=$this->shipment->seller_requisites['address']?>
        <br />
        Тел. <?=$this->shipment->seller_requisites['phone']?>
    </p>
    <p>
    	<span>Покупатель:</span>
        <br />
        <?=$this->shipment->client_requisites['name']?>,
        	<? if ( ! empty($this->shipment->client_requisites['inn'])) { ?>ИНН <?=$this->shipment->client_requisites['inn']?>,<? } ?>
        	<? if ( ! empty($this->shipment->client_requisites['kpp'])) { ?>КПП <?=$this->shipment->client_requisites['kpp']?>,<? } ?>
        <br />
        <? if ( ! empty($this->shipment->client_requisites['address'])) { ?>
            <?=$this->shipment->client_requisites['address']?>
        	<br />
        <? } ?>
        <? if ( ! empty($this->shipment->client_requisites['phone'])) { ?>Тел.: <?=$this->shipment->client_requisites['phone']?><? } ?>
    </p>
</div>
<form action="" method="POST" id="shipmentForm">
    <div class="ofzakaz_company">
    	<p><span>Город:</span> <?=$this->form->params__tr_city->setAttrib('style', 'width:475px')->render()?></p>
    </div>
    <div class="ofzakaz_company">
    	<? if ($this->form->params__tr_company_id->getErrors()) { ?>
    		<p><span style="color: red"><?=$this->translate('Выберите компанию-перевозчика')?></span></p>
    	<? } ?>
    	<p><span>Название транспортной компании:</span> <?=$this->form->params__tr_company_id->render()?></p>
    </div>
    <div class="ofzakaz_delivery_address">
    	<p>
        	<span>Доставка: <?=$this->form->params__ship_to->setAttrib('style', 'width: 435px;')->render()?></span>
            <br /><br />
            <? if ($this->form->params__ship_address->getErrors()) { ?>
            	<p><span style="color: red"><?=$this->translate('Необходимо указать адрес доставки')?></span></p>
            <? } ?>
            <?=$this->form->params__ship_address->setAttrib('style', 'display:none; width: 515px;')->render()?>
    	</p>
    	<br />
    	<a id="submitLink" href="<?=$this->url(array(), 'shop-order-shipment-prepare')?>"><img alt="Выбрать другую" src="<?=$this->skin()->url()?>images/predzakaz/make_order.jpg" /></a>    	
    </div>
</form>

<? $this->headScript(Zend_View_Helper_HeadScript::SCRIPT, '
	$(function(){
		var form = $("form#shipmentForm");
		$("select#params__tr_city", form).change(function(e){
			$.getJSON("'.$this->url(array(), 'shop-order-shipment-prepare-ajax').'", {act: "get-companies", city: $(this).val()}, function(resp){
				var id, name;
				var selectHtml = "<select name=\"params__tr_company_id\" id=\"params__tr_company_id\">";
				for (id in resp) {
					name = resp[id];
					selectHtml += "<option value=\""+id+"\">"+name+"</option>";
				}
				selectHtml += "</select>";
				$("select#params__tr_company_id", form).replaceWith(selectHtml);
				$("select#params__tr_company_id", form).val("'.$this->form->params__tr_company_id->getValue().'");
			});
		});
		$("select#params__tr_city", form).change();
		
		$("select#params__ship_to", form).change(function(e){
			var $this = $(this);
			if ($this.val()=="'.Checkout_Form_Shipment_TransportPrepare::SHIPMENT_TO_CLIENT.'") {
				$("textarea#params__ship_address").show();
			}
			else {
				$("textarea#params__ship_address").hide();
			}
		});
		$("select#params__ship_to", form).change();
		
		var TEXT_EMPTY_ADDRESS = "'.$this->translate('Введите адрес доставки').'";
		$("textarea#params__ship_address", form).focus(function(e){
			var area = $(this);
			if (area.text() == TEXT_EMPTY_ADDRESS) {
				area.html("");
			}
		});
		$("textarea#params__ship_address", form).blur(function(e){
			var area = $(this);
			var txt = area.text();
			if (txt.replace(/^\s\s*/, "").replace(/\s\s*$/, "") == "") {
				area.html(TEXT_EMPTY_ADDRESS);
			}
		});
		$("textarea#params__ship_address", form).blur();
		
		$("a#submitLink", form).click(function(e){
			e.preventDefault();
			var shipAddress = $("textarea#params__ship_address", form);
			if (shipAddress.text() == TEXT_EMPTY_ADDRESS) {
				shipAddress.html("");
			}
			form.submit();
		});
		
		
		
	});
') ?>
