<? foreach ($this->tips as $tip) { ?>

    <? $uid = uniqid('tip') ?>
    <? $id = 'tip_'.$tip->id ?>
    <div class="attention" uid="<?=$uid?>" id="<?=$id?>">
      <div class="wrapp">
        <? if ($tip->title) { ?>
        <strong><?=$tip->title?></strong><br />
        <? } ?>
        <?=$tip->text?><br />
      </div>
      <div style="float: right">
        <a href="#" uid="<?=$uid?>"><img src="<?=$this->skin()->url()?>images/close.gif" border="0"/>&nbsp;<?=$this->translate('закрыть')?></a>
      </div>
      <br/>
    </div>

    <?=$this->kosherInlineScript('
            $(function(){
                restoreStateXe("'.$id.'");
                $("a[uid='.$uid.']").unbind("click");
                $("a[uid='.$uid.']").click(function(e){
                    e.preventDefault();
                    $("div.attention[uid='.$uid.']").hide();
                    saveState("'.$id.'");
                });
            });
    ') ?>

<? } ?>