<script type="text/javascript">
    $(function() {
		var obj = $('ul.menu > li > a[href="<?= $_SERVER['REQUEST_URI']; ?>"]');
        var obj_sub = $('ul.menu li ul li a[href="<?= $_SERVER['REQUEST_URI']; ?>"]');
		obj.addClass('active');
        obj_sub.parent().parent().parent().find(' > a').addClass('active');
	});
</script>
<div class="center">
    <div class="line"></div>
    <a class="logo" href="<?=$this->url(array('reset'=>true), 'lab-index')?>"></a>

    <div class="cleaner"></div>
    <ul class="menu">

    </ul>
    <?= $this->box_Search();?>
</div>
<div class="cleaner"></div>