<? $counter = 0; ?>
<?foreach($this->items as $key => $item){?>
    <? $counter++; ?>
    <?= ( $counter == 1  ) ? '<div class="block left">' : ''?>
    <?= ( $counter == 6  ) ? '<div class="cleaner"></div><div class="block line">' : ''?>
    <?= ( $counter == 11  ) ? '<div class="block right">' : ''?>
        <div class="item <?= ( in_array($counter, array(2,3,8,12,13)) ) ? 'wide' : ''?><?= in_array($counter, array(5,10)) ? 'large' : ''?>" >
            <? if (in_array($counter, array(5,10)))
                    $preview = 'rc_id_preview4';
                elseif (in_array($counter, array(2,3,8,12,13)))
                    $preview = 'rc_id_preview3';
                else $preview = 'rc_id_preview2';
            ?>
            <a class="show_info" href="javascript:void(0);">
                <table class="items_align"><tr><td class="item_align">
                    <a class="items_align" href="<?=$this->url(array('category' => $item->category_seo_id, 'seo_id' => $item->seo_id), ( $item->category_seo_id == 'exclusive' ) ? 'shop-exclusive' : 'shop-item')?>">
                        <?if (isset($this->galleries[$item->id][0])){?>
                            <span><img  src="<?=App_Resource::getUploadsUrl($this->galleries[$item->id][0][$preview])?>" alt="" /><span>
                        <?}?>
                    </a>
                </td></tr></table>
            </a>
            <!--a class="show_info" href="javascript:void(0);"></a-->
            <a href="<?=$this->url(array('category' => $item->category_seo_id,'seo_id' => $item->seo_id), ( $item->category_seo_id == 'exclusive' ) ? 'shop-exclusive' : 'shop-item')?>">
            <div class="info">
                <div class="short">
                    <?= $item->brief?>
                    <!--?if( $item->price != 0 ){?>
                        <div class="price">ЦЕНА<span><?=$item->price?> грн.</span></div-->
                    <!--?}?-->
                    <div>ПОДРОБНЕЕ</div>
                </div>
            </div>
            </a>
        </div>
    <?= ( in_array($counter, array(4,9,14)) || $key+1 == count($this->items) && !in_array($counter, array(5, 10))) ? '</div>' : ''?>
    <?if ($counter == 14){ $counter = 0; }?>
<?}?>
