<script type="text/javascript">
    $(document).ready(function(){
        $(".cart_items a.delete").click(function(){
            $.post("<?=$this->url(array(), 'shop-cart-delete')?>", {hash: $(this).attr('rel')}, function(resp){
                $.post("<?=$this->url(array(), 'shop-cart-ajax-get-cart-box')?>", {}, function(data){
                        $('.cart_parent').html(data.cart);
                        $('.cart_items').html(data.pre_cart);
                        $('div[rel="'+$(this).attr('rel')+'"]').remove();
                }, 'json');
            });
        });

    });
</script>

<?if ( $this->totalQty > 0 ){?>
    <?$counter = 0;?>
    <?foreach ($this->items as $item){?>
        <?$counter++;?>
        <div rel="<?= $item->hash?>">
            <div class="itemcart">
            <img src="<?=App_Resource::getUploadsUrl($this->galleries[$item->seo_id][0]['rc_id_preview5'])?>" alt="" />
            </div>
            <a class="item" href="<?=$this->url(array('category' => $this->category->seo_id, 'seo_id' => $item->seo_id), 'shop-item')?>"><?= $key?><?= $item->name?> (<?= $item->qty?>)
                <div class="items_align">
                    <div class="item_align">
                        <img src="<?=App_Resource::getUploadsUrl($this->galleries[$item->seo_id][0]['rc_id_preview2'])?>" alt="" />
                    </div>
                </div>
            </a>
            <div class="cleaner"></div>
            <div class="characteristics">
                <?
                $specifications = (trim($item->material)) ? '<li><strong>Материал изделия:</strong> ' . $item->material . '</li>' : '';
                $specifications .= (trim($item->probe)) ? '<li><strong>Проба:</strong> ' . $item->probe . '</li>' : '';
                $specifications .= (trim($item->size)) ? '<li><strong>Размер изделия:</strong> ' . $item->size . ' мм</li>' : '';
                $specifications .= ($char = explode(', ', trim($item->characteristics)) and (null != $char[0])) ? '<li><strong>Вставки:</strong> ' . $char[0] . '</li>' : '';
                $specifications .= (trim($item->weight)) ? '<li><strong>Вес изделия:</strong> ' . $item->weight . ' г</li>' : '';
                ?>
                <?= $specifications ?>
            </div>
        </div>
        <a class="delete" href="javascript:void(0);" rel="<?= $item->hash?>"></a>
        <?//if ($counter == 2) {?>
            <div class="cleaner"></div>
            <?//$counter = 0;?>
        <?//}?>
    <?}?>
<?} else { ?>
    <div>В Вашей корзине нет товаров</div>
<? } ?>

