<?php echo '<script src="' . $this->baseUrl() . '/js/jquery.easing.min.js" type="text/javascript"></script>'; ?>

<script type="text/javascript">
//<![CDATA[
    $(function(){
        var cartTop = $('a.cart').offset().top;
        var cartLeft = $('a.cart').offset().left;
        $('a.to_cart').click(function() {
            var tv = $('.viewport td.item_align img.active');
            var clonedImage = tv.clone();
            $('body').append(clonedImage);
            var imageTop = tv.offset().top;
            var imageLeft = tv.offset().left;
            clonedImage.css({'position':'absolute', 'top':imageTop, 'left':imageLeft});
            clonedImage.animate({'top':cartTop, 'left':cartLeft, 'height':'50', 'width':'50'},
                {duration:700, easing:'easeOutBack', complete:function() {
                    $(this).hide();
                    $(this).remove();
                }});
        });
    });

    var preloaderState = false;
    function getBonus() {
            $('.preorder h2').html('РЕГИСТРАЦИЯ В БОНУСНОЙ ПРОГРАММЕ<a href="/page/registration-bonus" class="question" title="Условия получения бонуса"></a>');
            $('.cart_items').hide();
            $('.preorder').show();
        }

    function togglePreloader(){
        if (!preloaderState) {
            preloaderState = true;
            $('#preloader').show();
            $('#preorder_form .submit').die('click', aClick);
        } else {
            $('#preorder_form .submit').live('click', aClick);
            $('#preloader').hide();
            preloaderState = false;
        }
    }

    function aClick(){
        $('#preorder_form .error').html('');
        togglePreloader();
        $.ajax({
            type: "POST",
            url: "<?=$this->url(array(), 'shop-user-register')?>",
            data: $('#preorder_form').serialize(),
            dataType: "json"
        }).done(function(data) {
            if (data.success == true){
                $.each(data.values, function(i,v){
                    $('[name="'+i+'"]').val(v);
                });
                if (data.authorized == true){
                    $.ajax({
                        type: "POST",
                        url: "<?= $this->url(array(), 'shop-order-quick')?>",
                        data: $('#preorder_form').serialize(),
                        dataType: "json"
                    }).done(function(data) {
                        if (data.success == true){
                            $.each(data.values, function(i,v){
                                $('[name="'+i+'"]').val(v);
                            });
                            if (data.valid == false){
                                $.each(data.errors, function(i,v){
                                    if (i == 'items'){
                                        var $err = $('<ul></ul>').appendTo($('<div>').addClass('error').appendTo($('.cart_items')));
                                    } else {
                                        var $inp = $('[name="'+i+'"]');
                                        var $err = $('<ul></ul>').appendTo($inp.closest('div').find('.error'));
                                    }

                                    $.each(v, function(index, value){
                                        $('<li></li>').text(value).appendTo($err);
                                    });
                                });
                                $('#preorder_form .error').show();
                            } else {
                                if(data.errors) $('#after_order_popup').html('<div class="afterorder">Вы успешно зарегистрированы!<br /><br />Письмо с подтверждением отправлено Вам на электронную почту</div>');
                                $('.cart_parent').html(data.cart);
                                $('.cart_items').html(data.pre_cart);
                                $('#preorder_form').closest('.preorder').hide();
                                $('#after_order_popup').show();
                                setTimeout(function(){$('#after_order_popup').fadeOut('fast')},3000);
                            }
                        } else alert("Some problem occurred during operation.1");
                        togglePreloader();
                    }).error(function(data) {
                          alert("Some problem occurred during operation.2");
                          togglePreloader();
                    });
                } else if (data.valid === false){
                    $.each(data.errors, function(i,v){
                        var $inp = $('[name="'+i+'"]');
                        var $err = $('<ul></ul>').appendTo($inp.closest('div').find('.error'));
                        $.each(v, function(index, value){
                            $("<li></li>").text(value).appendTo($err);
                        });
                    });
                    $('#preorder_form .error').show();
                    togglePreloader();
                } else {
                    alert("Some problem occurred during operation.3");
                    togglePreloader();
                }
            } else {
                alert("Some problem occurred during operation.4");
                $("#dialog_status").val('Close');
                $("#dialog_message").show();

                togglePreloader();
            }
        }).error(function(data) {
              alert("Some problem occurred during operation.5");
              togglePreloader();
        });
        return false;
    }

    $(document).ready(function(){
        $(".checkout").live('click', function(){
            $('#preorder_form').closest('.preorder').show();
            $('.preorder h2').html('ФОРМА ЗАКАЗА ИЗДЕЛИЯ');
            $('.cart_items').show();
            $('.cart_detail').hide();
            $('#overlay_screen').show();
        });
        $('#preorder_form').submit(function(e){
            e.preventDefault();
        });
        $('#preorder_form .submit').live('click', aClick);

        $(".close").live('click', function(){
            //$(this).parent().hide();
            $('.preorder').hide();
            $('#overlay_screen').hide();
        });
    });
    $(document).click(function (event) {    		
        $('#after_order_popup').hide();
        $('#overlay_screen').hide();
    });
//]]>
</script>
<div id="after_order_popup" class="preorder">
    <span class="close"></span>
    <div class="afterorder">Спасибо за заказ!<br /><br />В ближайшее время менеджер свяжется с вами для уточнения деталей.</div>
</div>
<div class="preorder" style="min-height: 580px;">
    <span class="close"></span>
    <h2>ФОРМА РЕГИСТРАЦИИ И ЗАКАЗА ИЗДЕЛИЯ</h2>
    <form id="preorder_form" action="">
            <div class="cart_items">
                <?= $this->box_ShoppingCart('box/pre-shopping-cart.phtml')?>
            </div>
            <div class="cleaner"></div>
            <div>
                <div class="error"></div>
                <div class="remark">Имя и фамилия полностью</div>
                <label>ВАШЕ ИМЯ</label>
                <input name="name" type="text" tabindex="1"/>
                <span class="required">&nbsp;*</span>
            </div>
            <div>
                <div class="error"></div>
                <label>ЭЛ. ПОЧТА</label>
                <input name="email" type="text" tabindex="2"/>
                <span class="required">&nbsp;*</span>
            </div>
            <div class="cleaner"></div>
            <div>
                <div class="error"></div>
                <div class="remark">Телефон в международном формате</div>
                <label>ТЕЛЕФОН</label>
                <input name="telephone" type="text" tabindex="3" placeholder="+380ххххххххх"/>
                <span class="required">&nbsp;*</span>
            </div>
            <div class="cleaner"></div>
            <!-- div>
                <div class="error"></div>
                <label>ГОРОД</label>
                <input name="city" type="text" tabindex="4"/>
            </div-->
            <div class="cleaner"></div>
            <div>
                <div class="error"></div>
                <label>СООБЩЕНИЕ<br />МЕНЕДЖЕРУ</label>
                <textarea name="message" tabindex="5" rows="55" cols="3"></textarea>
            </div>
            <div class="cleaner"></div>
            <div class="submit_cantainer">
                <input class="submit" type="submit" value="ОТПРАВИТЬ" tabindex="6"/>
                <div id="preloader" class="preloader"></div>
            </div>
            <div class="cancel_cantainer">
                <input class="cancel close" type="submit" value="ОТМЕНИТЬ" tabindex="6"/>
                <div id="preloader_cancel" class="preloader"></div>
            </div>
        </form>
</div>
<div id="overlay_screen"></div>