<a href="javascript:void(0)" id="show_search" class="search show"></a>
<form id="quick_search" action="<?=$this->url(array(), 'shop-search')?>" method="get">
    <input name="text" type="text" />
    <a href="javascript:void(0)" class="search submit"></a>
</form>
<script type="text/javascript"> 
    $(document).ready(function(){
    
        $(function () {
            $('#show_search').click(function (e) {
                var $form = $('#quick_search');                    
                if ($form.css('display') != 'block') {
                    $(this).hide();
                    $form.show();   
                    $form.find('input').focus();
                    var yourClick = true;
                    $(document).bind('click.myEvent', function (e) {
                        if (!yourClick && $(e.target).closest('#quick_search').length == 0) {
                            $form.hide();
                            $('#show_search').show();                            
                            $(document).unbind('click.myEvent');
                        }
                        yourClick = false;
                    });
                  }             
              e.preventDefault();
            });
        });
        
        function removeSpaces(s) {
            var allSpacesRe = /\s+/g;
            return s.replace(allSpacesRe, ""); 
        }
        
        function validateAndSubmit(){
            var form = $('#quick_search');
            var text = removeSpaces( $('#quick_search input[name="text"]').val() );	

            if ( text.length > 0  )
                form.submit();
        }
        
        $('.search.submit').click(function(){
            validateAndSubmit();            
        })
        
/*        $('#quick_search input').keypress(function(e) {
            if(e.which == 13) {
                validateAndSubmit();      
                return false;
            }
        })
*/    })
</script>