
    <div class="content_col2">
          <div class="prod_details">
            <table cellspacing="0" class="prod_info info_detailed">
              <tr>
                <td colspan="2" style="padding-bottom: 14px;">
          <div class="catalog_h">
            <div class="catalog_h_r">
              <h2><?=$this->translate('Password recovery')?></h2>
            </div>
          </div>
                </td>
              </tr>
              <tr>

                <td><div class="box3">
                  <div class="box3-l">
                    <div class="box3-tl">
                      <div class="box3-tr">
                        <div class="box3-bl">
                          <div class="box3-br">
                            <div class="descriptions">
                              <p>
<? if ($this->submitted AND $this->success) { ?>
    <?=$this->translate('Thank you, you new password was emailed to you.')?>
<? } else { ?>
    <?=$this->renderForm($this->form)?>
<? } ?>
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div></td>
              </tr>
            </table>
        </div>
        <div class="cleaner">&nbsp;</div>





