<div class="conteiner">
    <div class="content">
        <span class="size22 colorred mypro"><?=$this->translate('NEWS')?></span>
    </div>
    <div class="content">
        <div class="conqiastions2"></div>
        <? foreach ($this->news as $row) { ?>
        <?if ($row['main_page']) continue;?>
        <div class="addnews">
            <span class="size15 bolt colorred"><?=$row['ntopic_name']?>: <?=$row['title']?></span><span class="flright bolt size15 colordark"><?=date('F j, Y', strtotime($row['date_publish']))?></span><br><br>
            <div class="image_div">
                <img src="<?=App_Resource::getUploadsUrl($row['rc_id_preview2'])?>" alt="<?=$row['title']?>"/>
                <div class="transparent_div"></div>
                <div class="transparent_div_text"><span class="title"><?=$row['title']?></span><br /><span class="title2"><?=$row['title2']?></span></div>
            </div>
            <?=$row['announce']?><br/><br/>
            <a class="read_more" href="<?=$this->url(array('seo_id' => $row['seo_id']), 'shop-news-detailed')?>"><?=$this->translate('READ MORE')?></a>
        </div>
        <?}?>
        <?=$this->paginationControl($this->news, NULL, 'catalog/pagination.phtml')?>
    </div>
</div>