<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'shop-index')?>">Главная<span></span></a>
        <a href="/pressroom">Советы консультанта<span></span></a>
	<span class="current"><?=$this->page->title ?></span>
        <? //print_r($this->news); ?>
    </div>
</div>
<div class="content page">
	<div class="center">
		<div class="news_detailed">
			<div class="head_links">
				<a class="left" href="/pressroom">&#8592; ПРЕСС-ЦЕНТР</a>
				<?if($this->next_seo_id != "") {?>
					<a class="right" href="/news/<?=$this->next_seo_id?>">СЛЕДУЮЩАЯ СТАТЬЯ &#8594;</a>
				<?}?>
			</div>
			<?if ($this->page->rc_id_filename) {?>
				<img class="news_title" src="/uploads/<?=$this->page->rc_id_filename ?>" width="960">
			<?}?>
			<div class="news_full">
				<h1><?=$this->page->title ?></h1>
				<?=$this->page->full ?><br/>
			</div>
			<div class="annoncement">
				РЕКОМЕНДУЕМ ПРОЧИТАТЬ<br />
				<?$i=1?>
				<?foreach($this->news_all as $onenews){?>
					<?if($i>3) break?>
					<?if($onenews->id == $this->page->id) continue?>
					<?//$img_src = App_Resource::getUploadsUrl($onenews['rc_id_preview2'])?>
					<img src="/uploads/<?=$onenews->rc_id_preview2 ?>" style="width:240px; height:155px; margin-top:20px" />
					<h3><a href="/news/<?=$onenews->seo_id?>">
						<?=$onenews->title?>
					</a></h3>
					<p><?=$onenews->announce?><p />
					<?$i++?>
				<?}?>
			</div>
			<div style="float:left; display:none">
				html_title - <?=$this->page->html_title ?><br/>
				date_added - <?=$this->page->date_added ?><br/>
				meta_description - <?=$this->page->meta_description ?><br/>
				meta_keywords - <?=$this->page->meta_keywords ?><br/>
			</div>
		</div>
	</div>
</div>