<div class="breadcrumbs">
    <div class="center">
        <a href="<?=$this->url(array('reset'=>true), 'shop-index')?>">Главная<span></span></a>
        <span class="current">ПРЕСС-ЦЕНТР</span>
        <? //print_r($this->news); ?>
    </div>
</div>
<div class="content page">    
    <div class="center">
        <div class="center">
            <div class="press_center">
                <span class="span_h2 page_title">ПРЕСС-ЦЕНТР</span>
                <div class="cleaner"></div>
                <? $i = 1; ?>
                <? if (isset($this->news) && count($this->news)) {?>
                    <? foreach ($this->news as $news) { ?>
                        <? $img_src = App_Resource::getUploadsUrl($news['rc_id_preview2']);?>
                        <? if ($i==1) {?>
                            <div id="<?=$news->seo_id?>" class="news_big">
                                <? if ( $img_src ) { ?>
                                    <a href="news/<?=$news->seo_id?>">
                                        <img src="<?= $img_src?>" alt="<?= $news['title']?>" width="650" height="350"/>
                                        <div class="fade" style="width: 650px;height:350px;margin-top:-350px;"></div>
                                    </a>
                                <?}?>
                                <a href="news/<?=$news->seo_id?>"><h2><?=$news->title?></h2>
                                <h3>что хорошо на каждый день</h3></a>
                        <?} elseif ($i==2) {?>
                            <div id="<?=$news->seo_id?>" class="news_small first">
                                <? if ( $img_src ) { ?>
                                    <a href="news/<?=$news->seo_id?>">
                                        <img src="<?= $img_src?>" alt="<?= $news['title']?>" width="290" height="165"/>
                                        <div class="fade" style="width: 290px;height:165px;margin-top:-165px;"></div>
                                    </a>
                                <?}?>
                                <a href="news/<?=$news->seo_id?>"><h2><?=$news->title?></h2></a>
                        <?} elseif ($i==3) {?>
                            <div id="<?=$news->seo_id?>" class="news_small second">
                                <? if ( $img_src ) { ?>
                                    <a href="news/<?=$news->seo_id?>">
                                        <img src="<?= $img_src?>" alt="<?= $news['title']?>" width="290" height="165"/>
                                        <div class="fade" style="width: 290px;height:165px;margin-top:-165px;"></div>
                                    </a>
                                <?}?>
                                <a href="news/<?=$news->seo_id?>"><h2><?=$news->title?></h2></a>
                        <?} else {?>
                            <div id="<?=$news->seo_id?>" class="news" data-id="<?= ($i % 2 != 0) ? 'second' : 'first'?>">
                                <? if ( $img_src ) { ?>
                                    <a href="news/<?=$news->seo_id?>"><img src="<?= $img_src?>" alt="<?= $news['title']?>" width="470" height="270"/></a>
                                <?}?>
                                <a href="news/<?=$news->seo_id?>"><h2><?=$news->title?></h2></a>
                                <?=$news->announce?><br><br>
                                <a href="news/<?=$news->seo_id?>" class="learn_more enabled">ЧИТАТЬ ПОЛНОСТЬЮ</a>
                        <?}?>
                        </div>
                        <? if ($i % 2 != 0 && $i > 2) {?>
                            <div class="cleaner"></div>
                        <?}?>
                        <? $i++ ?>
                    <?}?>
                <?} else {?>
                    <br />
                    <p>Скоро будет</p>
                <?}?>
                <div class="cleaner"></div>
            </div>            
        </div>
    </div>
    <script type="text/javascript">
        $(function() {
            $('.pc_item_small .learn_more.enabled').live('click', function() {
                var pc_item_id = $(this).closest('.pc_item').attr('id');
                $('.detailed').remove();
                if ($(this).closest('.pc_item_small').attr('data-id') == 'first') {
                    if ($(this).closest('.pc_item_small').next('[data-id="second"]').length > 0) {
                        $(this).closest('.pc_item_small').next('[data-id="second"]').after('<div class="cleaner"></div><div style="display:none;" class="detailed" data-seo_id="' + pc_item_id + '"><div class="cleaner"></div></div><div class="cleaner"></div>');
                    } else {
                        $(this).closest('.pc_item_small').after('<div class="cleaner"></div><div style="display:none;" class="detailed" data-seo_id="' + pc_item_id + '"><div class="cleaner"></div></div><div class="cleaner"></div>');
                    }
                } else {
                    $(this).closest('.pc_item_small').after('<div class="cleaner"></div><div style="display:none;" class="detailed" data-seo_id="' + pc_item_id + '"><div class="cleaner"></div></div><div class="cleaner"></div>');
                }
                $.ajax({
                    url: "<?= $this->stdUrl(array('reset' => TRUE), 'ajax-pressroom-full')?>",
                    type: "POST",
                    data: {seo_id : pc_item_id},
                    dataType: "json",
                    success: function(msg){
                        if (msg.success) {
                            $('.detailed').prepend(msg.full);
                            $('.pc_item_big tr:first-child td:first-child img:first-child').after('<h2>' + msg.title + '</h2><br><span class="pc_item_date">«' + msg.title2 + '», ' + msg.date + '</span>')
                            $('.detailed').show();
                        }
                    }
                });
                $('.pc_item').removeClass('pc_item_light');
                $(this).closest('.pc_item').addClass('pc_item_light');
                $('.learn_more').addClass('enabled').css('cursor', 'pointer');
                $(this).removeClass('enabled').css('cursor', 'default');
            });
            $('.pc_item_big .learn_more').live('click', function() {
                var pc_item_data_id = $(this).closest('.detailed').data('seo_id');
                $('.pc_item').removeClass('pc_item_light');
                $('.detailed').remove();
                $('#' + pc_item_data_id + ' .learn_more').addClass('enabled').css('cursor', 'pointer');
            });
        });
    </script>
</div>
