  <h3><a href="<?=$this->url(array(), 'news')?>"><?=$this->translate('Last News')?></a></h3>
  <div class="box_lnews">
    <ul class="menu">
      <? foreach ($this->data as $row) { ?>
      <li><a href="<?=$this->url(array('seo_id'=>$row['seo_id']), 'news_detailed')?>"><img src="<?=App_Resource::getUploadsUrl($row['rc_id_preview'])?>" alt="" width="45" height="45" border="0" /></a><a href="<?=$this->url(array('seo_id'=>$row['seo_id']), 'news_detailed')?>"><?=$row['title']?></a></li>
      <? } ?>
      <li class="last">&nbsp;</li>
    </ul>
  </div>


