  <div class="search">
    <div class="search_l">
      <div class="search_r">
        <div class="sfrm">
          <form action="<?=$this->stdUrl(NULL, 'go', 'search', 'kernel')?>" method="GET">
              <div><input type="text" name="q" class="query" /><input type="image" name="imageField2" src="<?=$this->skin()->url()?>images/btn_search.gif" class="btn_search" /></div>
              <div id="smenu">
                <ul>
                  <?/*?>
                  <li><a href="#" title="Агенства недвижимости"><span><img src="<?=App::$reg->url->skin?>images/head/icon_prods.gif" alt="" />Искать в товарах</span></a></li>
                  <li><a href="#" title="Издания"><span><img src="<?=App::$reg->url->skin?>images/head/icon_inet.gif" alt="" />Искать в интернете</span></a></li>
                  <li><a href="#" title="Банки"><span><img src="<?=App::$reg->url->skin?>images/head/icon_runet.gif" alt="" />Искать на страницах СНГ</span></a></li>
                  <?*/?>
                </ul>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>

