<?=$this->translate('Кому')?>: <?=$this->recipient->email?> (<?=$this->recipient->name?>)

<?=$this->translate('От')?>: <?=$this->sender->email?> (<?=$this->sender->firm_long?$this->sender->firm_long:$this->sender->name?>)

<?='#'.$this->msg->id.' '.$this->msg->subject?>

<?=$this->translate('Уведомление. Ваш клиент отправил письмо через веб сайт.')?>

<?=$this->translate('Клиент')?>:
    <?=$this->sender->firm_long?$this->sender->firm_long:$this->sender->name?>
    <?=$this->sender->email?>
    <?=$this->sender->phone?>

<?=$this->msg->body?>

<? $href = $this->host.$this->url(array('recipient_id'=>$this->sender->id, 'parent_id'=>$this->msg->id, 'authkey'=>$this->authKey), 'social_mail_new')?>

<?=$this->translate('Для быстрого ответа, перейдите по этой ссылке')?>: <?=$href?>

