<? $this->headScript('SCRIPT', '
	$(function(){
		$("a.qty-decrease").click(function(e){
			e.preventDefault();
			var parent = $(this).parent();
			var hash = parent.attr("hash");
			var newQty = $("#newQty_"+hash);
			var qty = newQty.val();
			if (qty > 0) {
				qty --;
			}
			newQty.val(qty);
			$("div.qty", parent).html(qty);
		});
		$("a.qty-increase").click(function(e){
			e.preventDefault();
			var parent = $(this).parent();
			var hash = parent.attr("hash");
			var newQty = $("#newQty_"+hash);
			var qty = newQty.val();
			if (qty < 1000000) {
				qty ++;
			}
			newQty.val(qty);
			$("div.qty", parent).html(qty);
		});
	});
')?>
		  <h1><?=$this->translate('Корзина')?></h1>
	        <div><img src="<?=$this->skin()->url()?>images/body/white-box-top-bg.png" width="746" height="10" border="0" /></div>
	        <form name="shopping_cart" method="POST" action="<?=$this->stdUrl(array('reset'=>TRUE), 'recalculate', 'cart', 'checkout')?>">
	        <div class="white-box-y vnutr basket">
				<div class="padd">
				  <div id="header-bs" >
				  	<div class="delete"><?=$this->translate('Удалить')?>:</div>
				  	<!-- div class="price-all"><?=$this->translate('Общая цена')?>:</div -->
				  	<div class="count"><?=$this->translate('Количество')?>:</div>
					<!-- div class="discn">Скидки:</div -->
					<div class="price"><?=$this->translate('Цена')?>:</div>
					<div class="title "><?=$this->translate('Наименование')?>:</div>
					<div class="image ">&nbsp;</div>
					<div class="cleaner"></div>
				  </div>
		    <? $i = 0 ?>
		    <? foreach ($this->items as $item) { ?>
				<div class="row">
				  	<!-- div class="price-all">5 270.52 грн</div -->
				  	<div class="delete"><input type="checkbox" name="del[<?=$item['hash']?>]" value="<?=$item['hash']?>" hash="<?=$item['hash']?>" /></div>
				  	<div class="count">
            <input type="hidden" value="<?=$item['qty']?>" name="newQty[<?=$item['hash']?>]" id="newQty_<?=$item['hash']?>" hash="<?=$item['hash']?>" />
            <input type="hidden" name="hash[<?=$item['hash']?>]" value="<?=$item['hash']?>" />
					  <div class="inc-box" hash="<?=$item['hash']?>">
					  		<a href="#" class="left-link qty-decrease" >-</a>
					  		<div class="text qty" hash="<?=$item['hash']?>"><?=$item['qty']?></div>
					  		<a href="#" class="right-link qty-increase" >+</a>
					  		<div class="cleaner"></div>
					  </div>				  	
					</div>
					<!--div class="discn">0 грн </div-->
					<div class="price"><?=$this->cart_Summ($item['price'])?></div>
					<div class="title"><a href="<?=$this->url(array('seo_id'=>$item['seo_id']), 'item')?>"><?=$item['name']?></a><br><?=$this->cart_ItemSpec($item)?></div>
					<div class="image"><a href="<?=$this->url(array('seo_id'=>$item['seo_id']), 'item')?>"><?=$this->html_Img($item['rc_id_preview'], 'width="116" height="80" border="0"', $item['rc_id_filename'])?></a></div>
					<div class="cleaner"></div>
				</div>
			<? } ?>
				<div class="footer">
					<?=$this->cart_Total($this->items)?>
					
				  
				  <div class="buttons"><div class="text"><?=$this->translate('Для удаления товара в поле “Количество” поставьте число “0”')?></div>
				  	<div class="box-basket"><a href="<?=$this->stdUrl(array('reset'=>TRUE), 'start', 'order', 'checkout')?>" class="basket-submit"><?=$this->translate('Оформить покупку')?></a></div>
					<div class="box-basket"><a href="#" class="basket-submit" onclick="document.shopping_cart.submit();return false;"><?=$this->translate('Пересчитать')?></a></div>
				</div>
				</div>
			</div>
				<div class="cleaner"></div>
		    </div>
		    </form>
            <div class="tag-bott-25"><img src="<?=$this->skin()->url()?>images/body/white-box-bott-bg.png" width="746" height="10" border="0" /></div>
