        <? if ($this->items->count()) { ?>
	        <h1><?=$this->translate('Альтернатива')?>:</h1>
	        <div><img src="<?=$this->skin()->url()?>images/body/white-box-top-bg.png" width="746" height="10" border="0" /></div>
	        <div class="white-box-y">
	           <? foreach ($this->items as $item) { ?>
	               <?=$this->item_ListThumb($item)?>
	           <? } ?>
			    <!-- div class="item">
			      <div class="image"><a href="#"><img src="<?=$this->skin()->url()?>images/examples/items/fishe-1.jpg" width="116" height="75" border="0" /></a></div>
			      <div class="link"><a href="#">Spro Roland Martin Signature Aruku Shad </a></div>
		          <div class="price"><a href="#"><img src="<?=$this->skin()->url()?>images/body/icon-basket.gif" width="14" height="15" border="0" /></a>  <div class="text">892.83 грн</div></div>
		        </div>
			    <div class="item">
			      <div class="image"><a href="#"><img src="<?=$this->skin()->url()?>images/examples/items/fishe-1.jpg" width="116" height="75" border="0" /></a></div>
			      <div class="link"><a href="#">Spro Roland Martin Signature Aruku Shad </a></div>
		          <div class="price"><a href="#"><img src="<?=$this->skin()->url()?>images/body/icon-basket.gif" width="14" height="15" border="0" /></a>  <div class="text">892.83 грн</div></div>
		        </div -->
			    <div class="cleaner"></div>
		    </div><div class="tag-bott-25"><img src="<?=$this->skin()->url()?>images/body/white-box-bott-bg.png" width="746" height="10" border="0" /></div>
        <? } ?>