  <? $itemsPerRow = 5 ?>
  <? $i = 0 ?>
  <? foreach ($this->items as $item) { ?>
        <?=$this->item_ListThumb($item)?>
        <? if (($i>0) AND ($i % $itemsPerRow == 0)) { ?>
            <div class="cleaner"></div>
        <? } ?>
        <? ++ $i ?>
  <? } ?>
  <? if ($i > 0) {  ?>
      <? while ($i % $itemsPerRow != 0) { ?>
        <div></div>
        <? ++ $i ?>
      <? } ?>
      <div class="cleaner"></div>
  <? } ?>