
<?=$this->menu('breadcrumbs')?>
    
    <div class="maket_header">
        <div class="mh_l">
            <p class="column_header"><?=$this->translate('Все бренды')?></p>
        </div>
    </div>
        
    <div class="novelties">
        <div class="novelties_inner">
    
    <? foreach ($this->manufacturers as $m) { ?>
            <div class="novelties_item">
                <a href="<?=$this->url(array('id'=>$m->id), 'shop-manufacturer')?>"><?=$m->name?></a>
            </div>
    <? } ?>
        </div>
    </div>
    

    <?=$this->paginationControl($this->manufacturers, NULL, 'catalog/pagination.phtml')?>