<?
        $this->menu()->addMenuBreadcrumbsPage(array(
            'label' => $this->translate('Счет № %1$s', $this->order->id),
            'route' => 'shop-my_order',
            'params' => array(
                'id' => $this->order->id,
            ),
        ));        

?>

<div class="container">
    <div id="content_left">
		
		<?=$this->box_Search()?>
		<?=$this->menu(Shop_View_Helper_Menu::MENU_BREADCRUMBS)?>
		
        <div class="content_header">
            <h1>Счет № <?=$this->order->id?> от <?=$this->formatDate($this->order->date_added)?></h1>
        </div><!-- .content_header -->

        <div class="cleaning">
        </div><!-- .cleaning-->

<?=$this->shipmentInfoHtml?>
<?=$this->paymentInfoHtml?>

        <div class="cleaning">
        </div><!-- .cleaning-->
			
            <table id="ordering_table" cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <td>№</td>
                        <td>Наименование товара</td>
                        <td>Цена</td>
                        <td>Кол-во</td>
                        <td>Сумма</td>
                    </tr>
                </thead>

                <tbody>
                
                    <? $i = 0 ?>
                    <? $totalQty = 0 ?>
                    <? foreach ($this->order->items as $item) { ?>
                        <tr>
                            <td><?=++$i?>.</td>
                            <td class="title"><a href="<?=$this->url(array('seo_id'=>$item['seo_id']), 'shop-item')?>"><?=$item['name']?></a><br><?=$this->order_ItemSpec($item)?></td>
                            <td class="price"><?=$this->order_Summ($item['price'])?></td>
                            <td class=""><?=$item['qty']?></td>
                            <td class="price"><?=$this->order_Summ($item['price'] * $item['qty'])?></td>
                        </tr>
                        <? $totalQty += $item['qty'] ?>
                    <? } ?>
                
                </tbody>
                
                    <tfoot>
                        <?=$this->order_Total($this->order, TRUE, FALSE, 'shop')?>                    
                    </tfoot>
                
            </table>

            
    </div><!-- #content_left-->       

</div><!-- .container-->

<div class="sidebar_right">
	<?=$this->box_News()?>
	
</div><!-- .sidebar_right -->







