<div class="index_cart">
	<div class="title_h3">
		<h3>Подтверждение заказа:</h3>
	</div>
	<p>Вы можете отменить свой заказ, просто закрыв окно браузера, либо подтвердить свой заказ, нажав кнопку <b>Подтвердить</b>.</p>
	
	<table id="confirm_order">
		<caption><strong>Товары:</strong>&nbsp;<a href="<?=$this->url(array(), 'shop-cart-index')?>" class="confirmationEdit">(Изменить)</a></caption>
		<?$totalPrice = 0;?>
		<? foreach ($this->items as $item) {?>
			<tr>
			    <td width="85%"><?=$item['qty']?> x <?=$item['name']?></td>
			    <td> <?=$item['qty']*$item['price']?> Р</td>
				<?$totalPrice = $totalPrice+$item['qty']*$item['price'];?>
			</tr>
		<?}?>
			<tr>
				<td><b>Всего</b>:</td>
				<td><b><?=$totalPrice;?></b></td>
			</tr>
	</table>
	<form id="checkout_confirmation" name="checkout_confirmation" action="<?=$this->url(array(), 'shop-order-finish')?>" method="post"> 
	    <input type="image" src="<?=$this->skin()->url()?>images/button_confirm_order.jpg" alt="Подтвердить Заказ" title=" Подтвердить Заказ " class="button" />
	</form>
	<a href="<?=$this->url(array(), 'shop-cart-index')?>"><img src="<?=$this->skin()->url()?>images/button_back.jpg" alt="Назад" title=" Назад " class="button_cart" style="border: none;" /></a>
</div>
  

