<? $uid = 'ordering_form'?>

<? $this->headScript(Zend_View_Helper_HeadScript::SCRIPT, '
	$(function(){
		$(".submit-order").click(function(e){
			e.preventDefault();
			$("#'.$uid.'").submit();
		});
	});
')?>



<? $errors = array_merge($this->form->getErrors(), $this->form->getErrorMessages()) ?>


<form  enctype="multipart/form-data"
    <? foreach ($this->form->getAttribs() as $name=>$value) { ?>
        <?=$name?>="<?=$value?>"
    <? } ?>
    method="POST"
    id="<?=$uid?>"
>
    <h1>Обязательные поля отмечены звездочкой <sup>*</sup></h1>
    


    <? $buttons = array() ?>
    <? $hiddens = array() ?>
    <? $inputs = array() ?>
    
    <? foreach ($this->form->getElements() as $el) {?>
        <? if (($el instanceof Zend_Form_Element_Submit) OR ($el instanceof Zend_Form_Element_Button)) { ?>
            <? $buttons[]=$el ?>
        <? } else if ($el instanceof Zend_Form_Element_Hidden) { ?>
            <? $hiddens[]=$el ?>
        <? } else { ?>
            <? $inputs[]=$el ?>
        <? } ?>
    <? } ?>
    
    <? foreach ($inputs as $el) {?>
        <? $label = $el->getLabel() ?>
        <? if ( ! empty($label)) { ?><p for="<?=$el->getName()?>"><?=$label?><? if ($el->isRequired()) {?> <?=$this->formMarkerRequired()?><? } ?></p><? } ?>
            <? if ($errors[$el->getName()]) { ?>
                <div class="red" style="color:red">
                <?=$this->form->getElementErrorsFormatted($el->getName(), $errors[$el->getName()])?>
                </div>
            <? } ?>
            <? if (in_array($el->getType(), array('Zend_Form_Element_Text', 'Zend_Form_Element_Password'))) { ?>
                    <? /*$el->setAttrib('class', 'input')*/ ?>
            <? } else if ($el->getType() == 'Zend_Form_Element_Select') { ?>
                    <? /*$el->setAttrib('class', 'select')*/ ?>
            <? } else if ($el->getType() == 'Zend_Form_Element_Textarea') { ?>
                    <? /*$el->setAttrib('class', 'textarea')*/ ?>
            <? } ?>
            <? $el->setDecorators(array('ViewHelper')) ?>
            <?=$el->render()?>
    <? } ?>
        
    <? foreach ($buttons as $btn) { ?>
        <?=$btn->render()?>
    <? } ?>

    <? foreach ($hiddens as $el) { ?><?=$el->render()?><? } ?>


</form>
<?/*?>
<form id="ordering_form" action="ordering_form.php" method="get">
    <h1>Обязательные поля отмечены звездочкой <sup>*</sup></h1>
    <p>Имя получателя <sup>*</sup></p>
    <input value="" type="text" id="recipient_name" />
    <p>Телефон <sup>*</sup></p>
    <input value="" type="text" id="phone" />
    <p class="comment">например, (067) 234-56-67</p>
    <p>Электронная почта</p>
    <input value="" type="text" id="email" />
    <p class="comment">Для отслеживания товара</p>
    <p>Способ доставки <a href="#">подробнее</a></p>
    <select id="delivery_method" size="1">
        <option value="Курьером">Курьером</option>
        <option value="Наложным платежом">Наложным платежом</option>
    </select>
    <p>Адрес доставки</p>
    <input value="" type="text" id="delivery_address" />
    <p>Комментарий</p>
    <textarea id="comment" name="comment" cols="30" rows="3"></textarea>
</form>
<?*/?>

