<div class="mcol">
      

<table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tbody><tr>
          <td class="main">&nbsp;</td>
        </tr>
</tbody></table>
<form id="checkout_address" name="checkout_address" action="<?=$this->url(array(), 'shop-order-quick')?>" method="post"><input type="hidden" name="action" value="process">

<table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tbody><tr>
          <td class="main">&nbsp;</td>
        </tr>
  <tr> 
    <td style="border-top: 1px solid; border-color: #cccccc;">
	  <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tbody><tr> 
          <td valign="top" class="main"><strong>Продолжить оформление заказа </strong><br>
            Перейти к выбору способа оплаты.<br> 
          </td>
          <td style="border-right: 1px solid; border-color: #cccccc;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tbody><tr> 
                <td align="center" valign="top" class="main"></td>
                <td class="main" align="center"><input type="image" src="<?=$this->skin()->url()?>images/button_continue.gif" alt="Продолжить" title=" Продолжить " class="buttons"></td>
              </tr>
            </tbody></table></td>
        </tr>
      </tbody></table></td>
  </tr>
</tbody></table>
</form>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tbody><tr>
          <td class="main">&nbsp;</td>
        </tr>
      <tr>
        <td>
        <table border="0" width="100%" cellspacing="0" cellpadding="0">
          <tbody><tr>
            <td align="right">
			<table border="0" width="50%" cellspacing="0" cellpadding="0">
              <tbody><tr>
                <td class="onepxwidth"><img src="<?=$this->skin()->url()?>images/checkout_bullet.gif" alt=""></td>
                <td><img src="<?=$this->skin()->url()?>images/pixel_silver.gif" width="100%" height="1" alt=""></td>
              </tr>
            </tbody></table></td>
            
          <td><img src="<?=$this->skin()->url()?>images/pixel_silver.gif" width="100%" height="1" alt=""></td>
          <td><img src="<?=$this->skin()->url()?>images/pixel_silver.gif" width="100%" height="1" alt=""></td>
            <td>
			  <table border="0" width="100%" cellspacing="0" cellpadding="0">
              <tbody><tr>
                <td><img src="<?=$this->skin()->url()?>images/pixel_silver.gif" width="100%" height="1" alt=""></td>
                <td><img src="<?=$this->skin()->url()?>images/pixel_silver.gif" width="1" height="1" alt=""></td>
              </tr>
            </tbody></table></td>
          </tr>
          <tr>            
          <td align="center" class="checkoutBarCurrent">Доставка</td>            
          
          <td align="center" class="checkoutBarTo">Подтверждение</td>            
          <td align="center" class="checkoutBarTo">Заказ оформлен</td>
          </tr>
        </tbody></table></td>
      </tr>
</tbody></table>
      
    </div>