				<div class="padd">
                  <? if ($this->parent) { ?>
                  <h1><?=$this->parent->name?></h1>
                  <? } ?>
                  <!-- div class="dott-sep"><img src="<?=$this->skin()->url()?>images/spacer.gif" width="705" height="10" border="0" /></div>
                  <div class="order">
                    <div class="title">Сортировать:</div>
                    <div class="box-link-active-desc"><a href="#" class="link-active">по цене</a> </div>
                    <div class="box-link-deactive"><a href="#" class="link-deactive">по наименованию</a></div>
                    <div class="select-box">
                        <div class="select-137"><select name="select-products" id="select-products"><option>Производители</option><option>- первый </option><option>- второй</option></select></div>
                        <a href="#" class="kurs-submitt">Выбрать</a>
                    </div>
                    <div class="cleaner"></div>
                  </div>
                  <div class="dott-sep"><img src="<?=$this->skin()->url()?>images/spacer.gif" width="705" height="10" border="0" /></div>
<div class="form-box">
                <div><img src="<?=$this->skin()->url()?>images/input-form/inp-form-top-bg.png" width="705" height="10" border="0" /></div>
              <div class="inp-form-y feat-form"><form action="/" name="feat-form" method="post">
                <div class="padd"><h3 >Подбор по характеристикам</h3><div class="link-open-box"><a href="#">раскрыть</a></div>
                <div class="cleaner"></div></div>
            </form>
                  </div>
              <div class="tag-bott"><img src="<?=$this->skin()->url()?>images/input-form/inp-form-bt-bg.png" width="705" height="10" border="0" /></div>
            </div>
            <div class="form-box">
                <div><img src="<?=$this->skin()->url()?>images/input-form/inp-form-top-bg.png" width="705" height="10" border="0" /></div>
              <div class="inp-form-y feat-form"><form action="/" name="feat-form" method="post">
                <div class="padd">
                      <h3 >Подбор по характеристикам</h3>
                      <div class="link-close-box"><a href="#">скрыть</a></div>
                  <div class="cleaner"></div>
                <div class="row brd-wt">
                    <div class="title">Параметр 1</div>
                    <div class="select-166"><select name="param1" id="param1"><option value="val1">Выбор 1-1</option><option value="val2">Выбор 1-2</option></select></div>
                    <div class="title first">Параметр 2</div>
                    <div class="select-333"><select name="param2" id="param2"><option value="val1">Выбор 1-1</option><option value="val2">Выбор 1-2</option></select></div>
                    <div class="cleaner"></div>
                </div>
                <div class="row brd-wb">
                    <div class="title">Параметр 3</div>
                    <div class="select-166"><select name="param3" id="param3"><option value="val1">Выбор 3-1</option><option value="val2">Выбор 3-2</option></select></div>
                    <div class="checkbox-box first"><input type="checkbox" id="check-4" value="action" name="checka"/><label for="check-4" >Параметр 4 </label></div>
                    <div class="checkbox-box"><input type="checkbox" id="check-5" value="action" name="checka"/><label for="check-5">Параметр 5 </label></div>
                    <div class="checkbox-box"><input type="checkbox" id="check-6" value="action" name="checka"/><label for="check-6">Параметр 6 </label></div>
                    <div class="cleaner"></div>
                </div>
                <div class="button-box"><a href="#" class="form-submit" onclick="document.feat-form.submit();">Применить</a></div>
                <div class="button-box-sep"><img src="<?=$this->skin()->url()?>images/spacer.gif" width="118" height="18" border="1" /></div><div class="cleaner"></div></div>
            </form>
                  </div>
              <div class="tag-bott"><img src="<?=$this->skin()->url()?>images/input-form/inp-form-bt-bg.png" width="705" height="10" border="0" /></div>
            </div>
            </div -->
            </div>
                <div class="cleaner"></div>
                <?=$this->item_ListThumbs($this->items)?>
                <?=$this->paginationControl($this->items, NULL, 'category/pagination.phtml')?>
                <div class="cleaner"></div>
