<? $this->pageTitle($this->translate('Товары')); ?>

<div class="widget-box collapsible">
    <div class="widget-title">
        <a href="#collapseTwo" data-toggle="collapse">
			<span class="icon"><i class="icon-search"></i></span>
                <h5><?=$this->translate('Поиск')?></h5>
        </a>
    </div>
    <div class="collapse" id="collapseTwo">
        <div class="widget-content">
                <?=$this->filter?>
        </div>
    </div>
</div>

<?=$this->siteSelectHtml?>
<?=$this->gotoHtml?>
<?=$this->adminMassForm('formStart')?>
<div class="widget-box collapsible">
    <div class="widget-title">
        <a href="#collapseThree" data-toggle="collapse">
			<span class="icon"><i class="icon-pencil"></i></span>
                <h5><?=$this->translate('Действия с товаром')?></h5>
        </a>
    </div>
    <div class="collapse" id="collapseThree">
        <div class="widget-content">
                <?=$this->adminMassForm('actions', $this->massActionsConfig)?>
        </div>
    </div>
</div>
<div class="widget-box table">
    <div class="widget-title"><h5><?=$this->translate('Список товаров')?></h5>
    <div class="buttons">
        <a href="<?=$this->stdUrl(array('reset'=>TRUE, 'category'=>$this->category), 'edit', 'admin-item_index', 'catalog')?>" class="btn btn-mini">
        <i class="icon-file"></i>
        <?=$this->translate('New')?>
        </a>        
    </div>
    </div>
    <div class="widget-content nopadding">  
<? $i = 0 ?>

    <table cellspacing="0" class="table table-bordered table-striped table-hover table-no-external-border">
      <tr>
        <th width="50px"><?=$this->adminMassForm('checkAll')?></th>
        <th width="70px" ><?=$this->translate('Image')?></th>
        <th><?=$this->translate('Артикул')?></th>
        <th><?=$this->translate('Название')?></th>
        <th><?=$this->translate('Seo id')?></th>
        <!--th width="10%"><?=$this->translate('Sorting')?></th-->        
        <!--th><?=$this->translate('Количество')?></th-->
        <!--th><?=$this->translate('Цена')?></th -->        
        <!--th><?=$this->translate('Состояние')?></th-->
        <!--th><?=$this->translate('Популярный')?></th-->
        <th class="actions2" width="12%"><?=$this->translate('Actions')?></th>
      </tr>

<? if ($this->items->count()) { ?>
    <? foreach ($this->items as $row) { ?>
          <tr>
            <td><?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
            <td style="text-align: center;">
				<? if(isset($this->galleries) and isset($this->galleries[$row->id][0])) { ?>
					<img style="max-width: 60px;" src="<?=App_Resource::getUploadsUrl($this->galleries[$row->id][0]['rc_id_preview2'])?>" alt="" />
				<? } ?>
			</td>
            <td><?=$row['sku']?></td>
            <td><?=$row['name']?></td>           
            <td><?=$row['seo_id']?></td>
            <!--td> <?=$this->adminListSorting(array('id'=>$row['id'], 'action'=>'sorting'))?></td-->
            <!--td><?/*=$row['attr_qty']*/?></td-->
            <!--td><?/*=$row['attr_price']*/?></td-->
            <!--td><?=$this->item_IsConfigurable($row)?></td-->
            <!--td><?=$row->is_popular?$this->translate('да'):''?></td-->
            <td class="actions2">
                <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit', 'admin-item_index', 'catalog')?>"><?=$this->translate('Edit')?></a>
                 /
                <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete', 'admin-item_index', 'catalog')?>"><?=$this->translate('Delete')?></a>
                <br/>
                <!--a class="act_edit" href="<?//=$this->stdUrl(array('contentId'=>$row['id'], 'contentType'=>base64_encode('catalog/item')), 'index', 'admin-comment', 'kernel')?>"><?//=$this->translate('Комментарии')?></a-->
            </td>
          </tr>

        <? ++$i ?>
    <? } ?>

<? } else { ?>
      <tr>
        <td colspan="6">
            <?=$this->translate('В этой категории пока нет объектов')?>
        </td>
      </tr>
<? } ?>

    </table>

</div>
    <?=$this->paginationControl($this->items)?>
    <?=$this->adminMassForm('formEnd')?>
</div>


