
<div style="width: 100%">
    <h2 style="float: left"><?=$this->translate('Статьи')?></h2>
    <div style="float: right"><?=$this->gotoHtml?></div>
</div>
<div class="cleaner">&nbsp;</div>

<?=$this->adminMassForm('formStart')?>
<?=$this->adminMassForm('actions')?>

<? $i = 0 ?>

    <table cellspacing="0" class="tbl">
      <tr>
        <th width="50px"><?=$this->adminMassForm('checkAll')?></th>
        <th width="100px"><?=$this->translate('Sorting')?></th>
        <th><?=$this->translate('Заголовок')?></th>
        <th><?=$this->translate('Seo Id')?></th>
        <? if ( ! $this->topicId) { ?>
            <th><?=$this->translate('Рубрика')?></th>
        <? } ?>
        <th class="actions2"><?=$this->translate('Actions')?></th>
      </tr>

<? if ($this->articles->count()) { ?>
    <? foreach ($this->articles as $row) { ?>
          <tr >
            <td> <?=$this->adminMassForm('check', array('id'=>$row['id']))?> </td>
            <td> <?=$this->adminListSorting(array('id'=>$row['id'], 'action'=>'sorting'))?></td>
            <td><?=$row['title']?></td>
            <td><?=$row['seo_id']?></td>
            <? if ( ! $this->topicId) { ?>
                <td><?=$row['topic_name']?></td>
            <? } ?>
            <td class="actions2">
                <a class="act_edit" href="<?=$this->stdUrl(array('id'=>$row['id']), 'edit', 'admin-article')?>"><?=$this->translate('Edit')?></a>
                 /
                <a class="act_delete" href="<?=$this->stdUrl(array('id'=>$row['id']), 'delete', 'admin-article')?>"><?=$this->translate('Delete')?></a>
                <br/>
                <a class="act_edit" href="<?=$this->stdUrl(array('contentId'=>$row['id'], 'contentType'=>base64_encode('article')), 'index', 'admin-comment')?>"><?=$this->translate('Комментарии')?></a>
            </td>
          </tr>

        <? ++$i ?>
    <? } ?>

<? } else { ?>
      <tr>
        <td colspan="6">
            <?=$this->translate('Пока нет статей связанных с этой темой')?>
        </td>
      </tr>
<? } ?>

    </table>


    <?=$this->adminMassForm('formEnd')?>

    <?=$this->paginationControl($this->articles)?>


  <a href="<?=$this->stdUrl(array('reset'=>TRUE, 'topic'=>$this->topicId), 'edit', 'admin-article')?>" class="btn2"><?=$this->translate('New')?></a>


