<h3><?=$this->translate('Users')?></h3>
<ul class="nav">
    <li><a href="<?=$this->stdUrl(array('id'=>NULL, 'page'=>NULL), 'index', 'admin-user')?>"><?=$this->translate('List all')?></a></li>
    <li class="last"><a href="<?=$this->stdUrl(array('id'=>NULL), 'edit', 'admin-user')?>"><?=$this->translate('Create new')?></a></li>
</ul>
<h3><?=$this->translate('Roles')?></h3>
<ul class="nav">
    <li><a href="<?=$this->stdUrl(array('id'=>NULL, 'page'=>NULL), 'index', 'admin-role')?>"><?=$this->translate('List all')?></a></li>
    <li class="last"><a href="<?=$this->stdUrl(array('id'=>NULL), 'edit', 'admin-role')?>"><?=$this->translate('Create new')?></a></li>
</ul>
